In [61]:
import pandas as pd 
import numpy as np
import re
import json

In [67]:
with open('../data/raw/categories/smartphones_results_over.json', 'r', encoding='utf-8') as f:
    data_smartphone = json.load(f) 
df_smartphone = pd.json_normalize(data_smartphone)

with open('../data/raw/categories/tablets_results_over.json', 'r', encoding='utf-8') as f:
    data_tablet = json.load(f)
df_tablet = pd.json_normalize(data_tablet)

with open('../data/raw/categories/laptop_results_over.json' , 'r' , encoding='utf-8') as f:
    data_laptop = json.load(f)
df_laptop = pd.json_normalize(data_laptop)

In [70]:
print(df_smartphone.info())
print(df_tablet.info())
print(df_laptop.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5486 entries, 0 to 5485
Columns: 218 entries, Category to Characteristics.Ортопедический
dtypes: object(218)
memory usage: 9.1+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5594 entries, 0 to 5593
Columns: 166 entries, Category to Characteristics.Размер воротника
dtypes: object(166)
memory usage: 7.1+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5411 entries, 0 to 5410
Columns: 228 entries, Category to Characteristics.Оригинальное название (для переводных изданий)
dtypes: object(228)
memory usage: 9.4+ MB
None

In [104]:
df_laptop.sample(3)

     Category                                               Name      Price    Old Price Installment Rating Reviews                  Seller Seller Rating                                                URL Characteristics.Артикул Characteristics.Обязательные программы предустановлены Characteristics.Процессор Characteristics.Общий объем SSD, ГБ                    Characteristics.Видеокарта Characteristics.Операционная система Characteristics.Диагональ экрана, дюймы Characteristics.Оперативная память Characteristics.Время автономной работы, ч Characteristics.Вес, кг Characteristics.Технология матрицы Characteristics.Тип памяти Characteristics.Модуль связи Bluetooth Characteristics.Материал корпуса Characteristics.Цвет Characteristics.Форм-фактор ноутбука Characteristics.Версия Windows Characteristics.Модель процессора Characteristics.Бренд процессора Characteristics.Частота процессора, ГГц Characteristics.Число ядер процессора Characteristics.Форм-фактор SSD Characteristics.Разрешение экрана Characteristics.Яркость, кд/м2 Characteristics.Сенсорный экран        Characteristics.Интерфейсы и разъемы Characteristics.Число портов HDMI Characteristics.Число портов USB 2.0 Characteristics.Число портов USB Type-A  3.2 Gen 1 Characteristics.Число портов USB Type-C Characteristics.Устройства ручного ввода Characteristics.Раскладка клавиатуры Characteristics.Подсветка клавиатуры Characteristics.Цвет клавиатуры Characteristics.Емкость аккумулятора, Втч Characteristics.Тип аккумулятора Characteristics.Гарантийный срок Characteristics.Покрытие экрана Characteristics.Тип видеокарты Characteristics.Бренд графического процессора Characteristics.Тип накопителя Characteristics.Количество SSD Characteristics.Макс. частота обновления, Гц Characteristics.Разрешение Web-камеры Characteristics.Шторка для веб-камеры Characteristics.Встроенные устройства           Characteristics.Модуль связи WiFi Characteristics.Особенности устройств ручного ввода Characteristics.Покрытие корпуса Characteristics.Страна-изготовитель Characteristics.Возможность расширения RAM, до Characteristics.Модуль сотовой связи Characteristics.Слоты RAM-памяти Characteristics.Бренд Characteristics.Оптический привод Characteristics.Видеопамять Characteristics.Чипсет Characteristics.Форм-фактор RAM Characteristics.Количество HDD Characteristics.Форм-фактор HDD Characteristics.Конфигурация звука Characteristics.Поддержка VR Characteristics.Кол-во элементов аккумулятора Characteristics.Напряжение адаптера питания Characteristics.Тип подсветки Characteristics.Картридер                       Characteristics.Конфигурация Characteristics.Сетевая карта Characteristics.Срок службы, лет Characteristics.Версия MacOS Characteristics.Число портов Thunderbolt Characteristics.Число портов USB Type-A 3.2 Gen 2 Characteristics.Число портов DisplayPort Characteristics.Общий объем HDD, ГБ Characteristics.Гарантия OZON Characteristics.Тип Characteristics.Вид чехла Characteristics.Материал Characteristics.Застежка Characteristics.Внешние размеры, мм Characteristics.Размеры основного отделения, мм Characteristics.Подходит для устройств Characteristics.Мин. диагональ, дюймы Characteristics.Макс. диагональ экрана, дюймы Characteristics.Вес товара, г Characteristics.Особенности Characteristics.Код ТРУ Characteristics.Сертификат Characteristics.Состав материала Characteristics.Коллекция Characteristics.Стиль Characteristics.Размер на модели Characteristics.Рост модели на фото Characteristics.Параметры модели на фото (ОГ-ОТ-ОБ) Characteristics.Российский размер Characteristics.Размер производителя Characteristics.Пол Characteristics.Материал подкладки Characteristics.Рисунок Characteristics.Модель Characteristics.Особенности модели Characteristics.Тип посадки Characteristics.Тип упаковки одежды Characteristics.Количество в упаковке Characteristics.Уход за вещами Characteristics.Ширина, см Characteristics.Модель ремня Characteristics.Вид пряжки Characteristics.Сезон Characteristics.Покрой Characteristics.Тип рукава Characteristics.Гарантия Characteristics.Сорт цветов Characteristics.Вид выпуска товара Characteristics.Вид мочалки Characteristics.Единиц в одном товаре Characteristics.Упаковка Characteristics.Партномер (артикул производителя) Characteristics.Объем, мл Characteristics.Форма выпуска Characteristics.Основа краски Characteristics.Область применения Characteristics.Степень блеска покрытия Characteristics.Резьба Characteristics.Количество, штук Characteristics.Тип питания Characteristics.Функциональные особенности Characteristics.Конструктивные особенности Characteristics.Режимы работы Characteristics.Максимальная мощность, Вт Characteristics.Тип патрона Characteristics.Крутящий момент, Нм Characteristics.Количество скоростей Characteristics.Макс. обороты на 1ой скорости, об./мин Characteristics.Макс. обороты на 2ой скорости, об./мин Characteristics.Макс. диаметр патрона, мм Characteristics.Напряжение аккумулятора Characteristics.Количество аккумуляторов в комплекте Characteristics.Класс инструмента Characteristics.Партномер Characteristics.Рост Characteristics.Вид застежки Characteristics.Декоративные элементы Characteristics.Размер по вороту Characteristics.Материал стельки Characteristics.Материал подошвы обуви Characteristics.Бренд в одежде и обуви Characteristics.Материал верха Characteristics.Длина стопы, см Characteristics.Вид застёжки Characteristics.Целевая аудитория Characteristics.Количество в упаковке, шт Characteristics.Высота, см Characteristics.Длина, см Characteristics.Праздник Characteristics.Для кого Characteristics.Вид спортивных игр Characteristics.Плотность, г/м2 Characteristics.Длина, м Characteristics.Объем, л Characteristics.Способ открытия бака Characteristics.Размещение мусорки Characteristics.Форма мусорного бака Characteristics.Страна бренда Characteristics.Материал подкладки обуви Characteristics.Посадка Characteristics.Тип пронации Characteristics.Спортивное назначение Characteristics.Количество модулей Characteristics.Монтаж Characteristics.Количество рядов Characteristics.Ширина, мм Characteristics.Высота, мм Characteristics.Глубина, мм Characteristics.Тип датчика Characteristics.Вид техники Characteristics.Внутренний материал Characteristics.Полнота Characteristics.Вид рабочей обуви Characteristics.Метод крепления подошвы Characteristics.Длина стельки, см Characteristics.Назначение рабочей обуви Characteristics.Особенности спортивной обуви Characteristics.Глубина, см Characteristics.Ориентация Characteristics.Конструкция стола Characteristics.Макс. нагрузка, кг Characteristics.Материал столешницы Characteristics.Материал фасада Characteristics.Материал подстолья Characteristics.Покрытие Characteristics.Количество ящиков Characteristics.Количество ножек Characteristics.Тип направляющих Characteristics.Толщина столешницы, мм Characteristics.Исполнение Characteristics.Назначение (помещение) Characteristics.Стиль дизайна Characteristics.Форма поставки Characteristics.Особенности конструкции и дизайна Characteristics.Виды парикмахерских ножниц Characteristics.Основной материал Characteristics.Модель ТС Characteristics.Ортопедический Characteristics.Автор на обложке Characteristics.Серия Characteristics.Год выпуска Characteristics.Тип бумаги в книге Characteristics.Тип обложки Characteristics.Тип книги Characteristics.Язык издания Characteristics.Количество страниц Characteristics.Размеры, мм Characteristics.ISBN Characteristics.Сохранность книги Characteristics.Возрастные ограничения Characteristics.Рекомендуемый возраст ребёнка Characteristics.Оригинальное название (для переводных изданий)
587    laptop  Redmi Book 14 2025 JYU4677CN Ноутбук 14", Inte...  669 038 ₸  2 768 700 ₸    55 754 ₸      5     150             ElectroShop           4.9  https://www.ozon.kz/product/redmi-book-14-2025...              3302605513                                                Нет          Intel Core i5-13420H                                 512                            Intel UHD Graphics                         Windows Home                                      14                              16 ГБ                                         13                    1.37                                IPS                    LPDDR5X                                    5.2                           Металл               Silver                            Ультрабук                Windows 11 Home                     Intel Core i5                            Intel                                     3.4                                     8                             M.2                         1920x1200                            300                             NaN  3.5 мм, HDMI, USB 2.0, USB Type-C, USB 3.2                                 1                                    1                                                  1                                       2                     Touchpad, Клавиатура                    Русская раскладка                                  NaN                          черный                                        56                              NaN                                1                         Матовое                     Встроенная                                         Intel                            SSD                              1                                           60                               1 Мпикс                                   NaN                            Web-камера  IEEE 802.11ac, IEEE 802.11n, IEEE 802.11ax                                                NaN                               NaN                               Китай                                            NaN                                  NaN                              NaN                 Redmi                       Отсутствует                         SMA                    NaN                             NaN                            NaN                             NaN                                NaN                          NaN                                           NaN                                         NaN                           NaN                       NaN                                             16/512                           NaN                              NaN                          NaN                                      NaN                                               NaN                                      NaN                                 NaN                           NaN                 NaN                       NaN                      NaN                      NaN                                 NaN                                             NaN                                    NaN                                   NaN                                           NaN                           NaN                         NaN                     NaN                        NaN                              NaN                       NaN                   NaN                              NaN                                 NaN                                                NaN                                NaN                                  NaN                 NaN                                NaN                     NaN                    NaN                                NaN                         NaN                                 NaN                                   NaN                            NaN                        NaN                          NaN                        NaN                   NaN                    NaN                        NaN                      NaN                         NaN                                NaN                         NaN                                   NaN                      NaN                                               NaN                       NaN                           NaN                           NaN                                NaN                                     NaN                    NaN                              NaN                         NaN                                        NaN                                        NaN                           NaN                                       NaN                         NaN                                 NaN                                  NaN                                                NaN                                                    NaN                                           NaN                                     NaN                                                NaN                                 NaN                       NaN                  NaN                          NaN                                   NaN                              NaN                              NaN                                    NaN                                    NaN                            NaN                             NaN                          NaN                               NaN                                       NaN                        NaN                       NaN                      NaN                      NaN                                NaN                             NaN                      NaN                      NaN                                  NaN                                NaN                                  NaN                           NaN                                      NaN                     NaN                          NaN                                   NaN                                NaN                    NaN                              NaN                        NaN                        NaN                         NaN                         NaN                         NaN                                 NaN                     NaN                               NaN                                     NaN                               NaN                                      NaN                                          NaN                         NaN                        NaN                               NaN                                NaN                                 NaN                             NaN                                NaN                      NaN                               NaN                              NaN                              NaN                                    NaN                        NaN                                    NaN                           NaN                            NaN                                               NaN                                        NaN                               NaN                       NaN                            NaN                              NaN                   NaN                         NaN                                NaN                         NaN                       NaN                          NaN                                NaN                         NaN                  NaN                               NaN                                    NaN                                           NaN                                                NaN

In [37]:
df_tablet.sample(3)

     Category                                               Name     Price  Old Price Installment Rating Reviews                  Seller Seller Rating                                                URL Characteristics.Артикул Characteristics.Обязательные программы предустановлены Characteristics.Диагональ экрана, дюймы Characteristics.Беспроводные интерфейсы Characteristics.Оперативная память Characteristics.Операционная система Characteristics.Встроенная память,  ГБ Characteristics.Разрешение экрана          Characteristics.Процессор Characteristics.Разрешение основной камеры, Мпикс Characteristics.Технология матрицы Characteristics.Стандарты связи Characteristics.Тип Characteristics.Бренд     Characteristics.Цвет Characteristics.Год анонсирования Characteristics.Версия Android Characteristics.Частота обновления экрана, Гц Characteristics.Плотность пикселей, ppi Characteristics.Бренд процессора Characteristics.Число ядер процессора Characteristics.Частота процессора, ГГц Characteristics.Бренд графического процессора Characteristics.Видеопроцессор Characteristics.Модуль сотовой связи Characteristics.Форм-фактор SIM Characteristics.Число физических SIM-карт Characteristics.Модуль связи Bluetooth Characteristics.Модуль связи WiFi    Characteristics.Навигация Characteristics.Разъемы Characteristics.Назначение слотов Characteristics.Слот для карты памяти Characteristics.Тип карты памяти Characteristics.Макс. объем карты памяти,  ГБ Characteristics.Разрешение фронтальной (селфи) камеры, Мпикс Characteristics.Наличие клавиатуры Characteristics.Основной материал корпуса Characteristics.Защита от влаги Characteristics.Емкость аккумулятора, мАч Characteristics.Работа в режиме телефона Characteristics.Аксессуары в комплекте Characteristics.Размеры, мм Characteristics.Вес товара, г Characteristics.Гарантийный срок Characteristics.Страна-изготовитель Characteristics.Встроенные датчики      Characteristics.Функции камеры                        Characteristics.Особенности Characteristics.Макс. время работы (музыка),  ч Characteristics.Макс. время работы (видео),  ч Characteristics.Работа в режиме ожидания, ч Characteristics.Срок службы, лет Characteristics.Версия iOS Characteristics.Версия HarmonyOS Characteristics.Размер упаковки (Длина х Ширина х Высота), см Characteristics.Гарантия OZON Characteristics.Материал Characteristics.Состав материала Characteristics.Коллекция Characteristics.Стиль Characteristics.Размер на модели Characteristics.Рост модели на фото Characteristics.Параметры модели на фото (ОГ-ОТ-ОБ) Characteristics.Российский размер Characteristics.Размер производителя Characteristics.Пол Characteristics.Материал подкладки Characteristics.Рисунок Characteristics.Модель Characteristics.Особенности модели Characteristics.Тип посадки Characteristics.Тип упаковки одежды Characteristics.Количество в упаковке Characteristics.Уход за вещами Characteristics.Ширина, см Characteristics.Модель ремня Characteristics.Вид пряжки Characteristics.Код ТРУ Characteristics.Сертификат Characteristics.Сезон Characteristics.Покрой Characteristics.Тип рукава Characteristics.Гарантия Characteristics.Партномер (артикул производителя) Characteristics.Вид чехла Characteristics.Текстура Characteristics.Особенности состава Characteristics.Водостойкость Characteristics.Особенность оттенка Characteristics.Целевая аудитория Characteristics.Единиц в одном товаре Characteristics.Вес, г Characteristics.Упаковка Characteristics.Длина, см Characteristics.Вид застежки Characteristics.Признак 18+ Characteristics.Рост Characteristics.Декоративные элементы Characteristics.Размер по вороту Characteristics.Тип молотка Characteristics.Вес бойка, г Characteristics.Материал рукоятки Characteristics.Форма бойка Characteristics.Материал бойка Characteristics.Партномер Characteristics.Длина, мм Characteristics.Количество в упаковке, шт Characteristics.Вид аксессуара, запчасти Characteristics.Материал стельки Characteristics.Материал подошвы обуви Characteristics.Бренд в одежде и обуви Characteristics.Материал верха Characteristics.Длина стопы, см Characteristics.Вид застёжки Characteristics.Количество предметов Characteristics.Количество персон Characteristics.Материал столового прибора Characteristics.Ручка Characteristics.Покрытие приборов Characteristics.Подарочная упаковка в комплекте Characteristics.Подставка в комплекте Characteristics.Праздник Characteristics.Для кого Characteristics.Вид выпуска товара Characteristics.Вид техники Characteristics.Место установки Characteristics.Количество, штук Characteristics.OEM-номер Characteristics.Спортивное назначение Characteristics.Страна бренда Characteristics.Материал подкладки обуви Characteristics.Посадка Characteristics.Тип пронации Characteristics.Внутренний материал Characteristics.Полнота Characteristics.Вид рабочей обуви Characteristics.Метод крепления подошвы Characteristics.Длина стельки, см Characteristics.Назначение рабочей обуви Characteristics.Особенности спортивной обуви Characteristics.Застежка Characteristics.Внешние размеры, мм Characteristics.Размеры основного отделения, мм Characteristics.Подходит для устройств Characteristics.Мин. диагональ, дюймы Characteristics.Макс. диагональ экрана, дюймы Characteristics.Вид мягкой игрушки Characteristics.Высота игрушки, см Characteristics.Вид шумопоглощения Characteristics.Ортопедический Characteristics.Расположение сиденья Characteristics.Кузов Characteristics.Спинка Characteristics.Размер циферблата Characteristics.Размер воротника
2978  tablets  DASDG IA Планшет, 12" 16 ГБ/1024 ГБ, светло-зе...  80 156 ₸  427 352 ₸     6 680 ₸    4.8     112  новый продавец комп...           4.8  https://www.ozon.kz/product/dasdg-ia-planshet-...              3081701762                                                Нет                                          12                   Bluetooth, Wi-Fi, GPS                              16 ГБ                              Android                                   1024                         3840x2160                     Snapdragon 888                                                16                                IPS                    4G (LTE), 5G             Планшет                   NaN  Светло-зеленый, голубой                              2025                     Android 14                                           NaN                                     NaN                         Qualcomm                                     8                                       2                                           NaN                            NaN                                   Да                       Micro-SIM                                         2                                 4.2+LE          802.11 a/b/g/n/ac/ax/axe                          GPS      3.5 мм, USB Type-C            Гибрид (SIM 2/microSD)                                    Да                               SD                                          1024                                                  8                                          NaN                   Металл, Пластик, Стекло                              Да                                     12000                                       Да                             Клавиатура                  200*150*20                           500                           1 года                               Китай       GPS-трекер, Гироскоп, Компас                                 NaN  Встроенный микрофон, Игровые кнопки, Поддержка...                                             NaN                                            NaN                                         NaN                              NaN                        NaN                              NaN                                                NaN                                      NaN                      NaN                              NaN                       NaN                   NaN                              NaN                                 NaN                                                NaN                                NaN                                  NaN                 NaN                                NaN                     NaN                    NaN                                NaN                         NaN                                 NaN                                   NaN                            NaN                        NaN                          NaN                        NaN                     NaN                        NaN                   NaN                    NaN                        NaN                      NaN                                               NaN                       NaN                      NaN                                 NaN                           NaN                                 NaN                               NaN                                   NaN                    NaN                      NaN                       NaN                          NaN                         NaN                  NaN                                   NaN                              NaN                         NaN                          NaN                               NaN                         NaN                            NaN                       NaN                       NaN                                       NaN                                      NaN                              NaN                                    NaN                                    NaN                            NaN                             NaN                          NaN                                  NaN                               NaN                                        NaN                   NaN                               NaN                                             NaN                                   NaN                      NaN                      NaN                                NaN                         NaN                             NaN                              NaN                       NaN                                   NaN                           NaN                                      NaN                     NaN                          NaN                                 NaN                     NaN                               NaN                                     NaN                               NaN                                      NaN                                          NaN                      NaN                                 NaN                                             NaN                                    NaN                                   NaN                                           NaN                                NaN                                NaN                                NaN                            NaN                                  NaN                   NaN                    NaN                               NaN                              NaN
4546  tablets          Планшет16 ГБ/1024 ГБ, серый, светло-серый  53 990 ₸  175 229 ₸     4 500 ₸    4.8      62       ACC03 Электрон 3C           4.2  https://www.ozon.kz/product/planshet16-gb-1024...              3187856381                                                 Да                                         NaN                   Bluetooth, Wi-Fi, GPS                              16 ГБ                              Android                                   1024                         2560x1600                     Snapdragon 888                                                30                                IPS                             NaN             Планшет                   NaN      Серый, светло-серый                              2026                     Android 15                                         60 Гц                                     100                         Qualcomm                                     8                                    2.84                                      Qualcomm                            NaN                                  NaN                             NaN                                       NaN                                    5.3                               NaN  A-GPS, Beidou, GPS, ГЛОНАСС      3.5 мм, USB Type-C                           microSD                                    Да                          microSD                                           128                                                 16                                         Есть          Металл, Полимер, Титановый сплав                              Да                                     12000                                       Да                     Клавиатура, Стилус                   240*160*8                           450                            14дне                               Китай                          Спидометр                      Двойная камера  Встроенный микрофон, Громкая связь, Стилус, Фо...                                               5                                              4                                          12                                5                        NaN                              NaN                                                NaN                                      NaN                      NaN                              NaN                       NaN                   NaN                              NaN                                 NaN                                                NaN                                NaN                                  NaN                 NaN                                NaN                     NaN                    NaN                                NaN                         NaN                                 NaN                                   NaN                            NaN                        NaN                          NaN                        NaN                     NaN                        NaN                   NaN                    NaN                        NaN                      NaN                                               NaN                       NaN                      NaN                                 NaN                           NaN                                 NaN                               NaN                                   NaN                    NaN                      NaN                       NaN                          NaN                         NaN                  NaN                                   NaN                              NaN                         NaN                          NaN                               NaN                         NaN                            NaN                       NaN                       NaN                                       NaN                                      NaN                              NaN                                    NaN                                    NaN                            NaN                             NaN                          NaN                                  NaN                               NaN                                        NaN                   NaN                               NaN                                             NaN                                   NaN                      NaN                      NaN                                NaN                         NaN                             NaN                              NaN                       NaN                                   NaN                           NaN                                      NaN                     NaN                          NaN                                 NaN                     NaN                               NaN                                     NaN                               NaN                                      NaN                                          NaN                      NaN                                 NaN                                             NaN                                    NaN                                   NaN                                           NaN                                NaN                                NaN                                NaN                            NaN                                  NaN                   NaN                    NaN                               NaN                              NaN

In [38]:
df_smartphone.sample(3)

         Category                                               Name      Price  Old Price Installment Rating Reviews            Seller Seller Rating                                                URL Characteristics.Артикул Characteristics.Обязательные программы предустановлены Characteristics.Диагональ экрана, дюймы Characteristics.Емкость аккумулятора, мАч Characteristics.Процессор Characteristics.Беспроводные интерфейсы Characteristics.Разрешение экрана Characteristics.Число ядер процессора Characteristics.Оперативная память Characteristics.Встроенная память Characteristics.Разрешение основной камеры, Мпикс Characteristics.Цвет Characteristics.Тип Characteristics.Версия смартфона Characteristics.Восстановленный Characteristics.Операционная система Characteristics.Частота обновления экрана, Гц Characteristics.Технология матрицы Characteristics.Бренд процессора Characteristics.Частота процессора, ГГц Characteristics.Стандарты связи Characteristics.Форм-фактор SIM Characteristics.Поддержка eSim Characteristics.Число физических SIM-карт Characteristics.Модуль связи Bluetooth Characteristics.Модуль связи WiFi Characteristics.Аутентификация      Characteristics.Навигация Characteristics.Интерфейсы Characteristics.Слот для карты памяти      Characteristics.Функции камеры   Characteristics.Стабилизация Characteristics.Количество основных камер Characteristics.Разрешение фронтальной (селфи) камеры, Мпикс Characteristics.Качество видео Characteristics.Тип корпуса Characteristics.Степень защиты Characteristics.Функции зарядки Characteristics.Размеры, мм Characteristics.Вес товара, г Characteristics.Гарантийный срок Characteristics.Страна-изготовитель                 Characteristics.Встроенные датчики Characteristics.Основной материал корпуса Characteristics.Тип карты памяти Characteristics.Версия Android                        Characteristics.Особенности Characteristics.Бренд графического процессора Characteristics.Видеопроцессор Characteristics.Макс. объем карты памяти,  ГБ Characteristics.Макс. скорость видеосъемки, кадр/с Characteristics.Работа в режиме ожидания, ч Characteristics.Время работы в режиме разговора, ч Characteristics.Бренд Characteristics.Срок службы, лет Characteristics.Версия iOS Characteristics.Гарантия OZON Characteristics.Версия HarmonyOS Characteristics.Код ТРУ Characteristics.Сертификат Characteristics.Код изделия Characteristics.Вид сифона Characteristics.Назначение сифона Characteristics.Количество предметов в комплекте Characteristics.Направление выпуска Characteristics.Перелив Characteristics.Длина, мм Characteristics.Ширина, мм Characteristics.Высота, мм Characteristics.Диаметр слива, мм Characteristics.Диаметр подключения сифона, см Characteristics.Сливной диаметр Characteristics.Комплектация Characteristics.Материал Characteristics.Гарантия Characteristics.Покрытие Characteristics.Вид посадочного материала Characteristics.Время урожая Characteristics.Время цветения Characteristics.Фасовка, кг Characteristics.Место для выращивания Characteristics.Время посадки на рассаду Characteristics.Время посадки в грунт Characteristics.Регион выращивания Characteristics.Жизненный цикл Characteristics.Назначение посадочного материала Characteristics.Вид стекла Characteristics.Твердость стекла Characteristics.Дополнительные свойства покрытия Characteristics.Толщина стекла, мм Characteristics.Применение Characteristics.Прозрачность покрытия Characteristics.Назначение пленки/стекла Characteristics.Количество в упаковке, шт Characteristics.Область использования Characteristics.Целевая аудитория Characteristics.Возрастной диапазон Characteristics.Единиц в одном товаре Characteristics.Объем, мл Characteristics.Вес, г Characteristics.Форма выпуска Characteristics.Длина щетки, см Characteristics.Длина второй щетки, см Characteristics.Количество, штук Characteristics.Крепление Characteristics.Вид техники Characteristics.Сезон Characteristics.Конструкция щетки Characteristics.Вид щетки Characteristics.Партномер (артикул производителя) Characteristics.Состав материала Characteristics.Коллекция Characteristics.Стиль Characteristics.Размер на модели Characteristics.Рост модели на фото Characteristics.Параметры модели на фото (ОГ-ОТ-ОБ) Characteristics.Российский размер Characteristics.Размер производителя Characteristics.Пол Characteristics.Материал подкладки Characteristics.Рисунок Characteristics.Модель Characteristics.Особенности модели Characteristics.Тип посадки Characteristics.Тип упаковки одежды Characteristics.Количество в упаковке Characteristics.Уход за вещами Characteristics.Ширина, см Characteristics.Модель ремня Characteristics.Вид пряжки Characteristics.Покрой Characteristics.Тип рукава Characteristics.Размер упаковки (Длина х Ширина х Высота), см Characteristics.Длина, см Characteristics.Количество элементов, шт Characteristics.Особенности конструктора Characteristics.Вид конструктора Characteristics.Совместим с LEGO Characteristics.Пол ребенка Characteristics.Тематика конструкторов Characteristics.Вид застежки Characteristics.Признак 18+ Characteristics.Высота, см Characteristics.Вид принта Characteristics.Вид крепления штор Characteristics.Состав комплекта Characteristics.Плотность ткани, г/кв.м Characteristics.Назначение (помещение) Characteristics.Рост Characteristics.Декоративные элементы Characteristics.Размер по вороту Characteristics.Материал стельки Characteristics.Материал подошвы обуви Characteristics.Бренд в одежде и обуви Characteristics.Материал верха Characteristics.Длина стопы, см Characteristics.Вид застёжки Characteristics.Диаметр, см Characteristics.Дизайн Characteristics.Количество предметов Characteristics.Особенности посуды Characteristics.Страна бренда Characteristics.Материал подкладки обуви Characteristics.Посадка Characteristics.Тип пронации Characteristics.Спортивное назначение Characteristics.Число секций Characteristics.Рекомендуемая площадь, м² Characteristics.Межосевое расстояние, мм Characteristics.Вид крепления Characteristics.Вид термостата Characteristics.Вид теплоносителя Characteristics.Диаметр соединения Characteristics.Теплоотдача, Вт Characteristics.Толщина, мм Characteristics.Конструктивные особенности Characteristics.Боковое подключение Characteristics.Установка Characteristics.Подключение Characteristics.Длина большей стороны, см Characteristics.Длина меньшей стороны, см Characteristics.Оформление Characteristics.Ширина рамы, см Characteristics.Цвет рамки Characteristics.Техника исполнения Characteristics.Вид чехла Characteristics.Застежка Characteristics.Подходит для устройств Characteristics.Внутренний материал Characteristics.Полнота Characteristics.Вид рабочей обуви Characteristics.Метод крепления подошвы Characteristics.Длина стельки, см Characteristics.Назначение рабочей обуви Characteristics.Особенности спортивной обуви Characteristics.Рядность карниза Characteristics.Длина карниза, см Characteristics.Раздвижной карниз Characteristics.Диаметр, мм Characteristics.Вид карниза Characteristics.Конфигурация карниза Characteristics.Крепление карниза Characteristics.Стиль дизайна Characteristics.Материал карниза Characteristics.С подхватом Characteristics.Плотность плетения ткани Characteristics.Вид выпуска товара Characteristics.Ортопедический
1323  smartphones  Смартфон H0N0R X9d Смартфон Глобальная русская...   52 426 ₸  637 436 ₸     4 369 ₸    4.9      74  PAGRAER Byte Hub           4.1  https://www.ozon.kz/product/smartfon-h0n0r-x9d...              3617722048                                                Нет                                         6.5                                      6200                 Helio P60                   Bluetooth, Wi-Fi, GPS                         2340x1080                                     8                              12 ГБ                            512 ГБ                                                48           Фиолетовый            Смартфон                               EU                             Нет                              Android                                           NaN                                TFT                         MediaTek                                       2                3G, 4G (LTE), 2G                        Nano-SIM                 SIM (без eSIM)                                         3                                    5.1              802.11 a/b/g/n/ac/ax             Распознавание лица                     A-GPS, GPS         3.5 мм, USB Type-C                                    Да             Широкоугольный объектив  AIS (стабилизация на базе ИИ)                                         3                                                 16                        1920x1080 Full HD                    Моноблок                            NaN                             NaN             155mm*75mm*10mm                           165                       12 месяцев                               Китай  Датчик распознавания лица, GPS-трекер, Акселер...                                    Стекло                          microSD                     Android 14  Физическая лампочка-индикатор, Поддержка OTG (...                                           ARM                   Mali-G73 MP3                                           512                                                 30                                         220                                                 24                   NaN                              NaN                        NaN                           NaN                              NaN                     NaN                        NaN                         NaN                        NaN                               NaN                                              NaN                                 NaN                     NaN                       NaN                        NaN                        NaN                               NaN                                            NaN                             NaN                          NaN                      NaN                      NaN                      NaN                                       NaN                          NaN                            NaN                         NaN                                   NaN                                      NaN                                   NaN                                NaN                            NaN                                              NaN                        NaN                              NaN                                              NaN                                NaN                        NaN                                   NaN                                      NaN                                       NaN                                   NaN                               NaN                                 NaN                                   NaN                       NaN                    NaN                           NaN                             NaN                                    NaN                              NaN                       NaN                         NaN                   NaN                               NaN                       NaN                                               NaN                              NaN                       NaN                   NaN                              NaN                                 NaN                                                NaN                                NaN                                  NaN                 NaN                                NaN                     NaN                    NaN                                NaN                         NaN                                 NaN                                   NaN                            NaN                        NaN                          NaN                        NaN                    NaN                        NaN                                                NaN                                  NaN                                      NaN                                      NaN                              NaN                              NaN                         NaN                                    NaN                          NaN                         NaN                        NaN                        NaN                                NaN                              NaN                                     NaN                                    NaN                  NaN                                   NaN                              NaN                              NaN                                    NaN                                    NaN                            NaN                             NaN                          NaN                         NaN                    NaN                                  NaN                                NaN                           NaN                                      NaN                     NaN                          NaN                                   NaN                          NaN                                       NaN                                      NaN                           NaN                            NaN                               NaN                                NaN                             NaN                         NaN                                        NaN                                 NaN                       NaN                         NaN                                       NaN                                       NaN                        NaN                             NaN                        NaN                                NaN                       NaN                      NaN                                    NaN                                 NaN                     NaN                               NaN                                     NaN                               NaN                                      NaN                                          NaN                              NaN                               NaN                               NaN                         NaN                         NaN                                  NaN                               NaN                           NaN                              NaN                         NaN                                      NaN                                NaN                            NaN

In [105]:
cols_to_fix = ['Price', 'Old Price', 'Installment']

df_smartphone[cols_to_fix] = df_smartphone[cols_to_fix].apply(lambda x: x.str.replace(r'\D', '', regex=True))
df_tablet[cols_to_fix] = df_tablet[cols_to_fix].apply(lambda x: x.str.replace(r'\D', '', regex=True))
df_laptop[cols_to_fix] = df_laptop[cols_to_fix].apply(lambda x: x.str.replace(r'\D', '', regex=True))

In [106]:

tablet_handle_list = ['Characteristics.Оперативная память','Characteristics.Тип',
'Characteristics.Частота обновления экрана, Гц',
'Characteristics.Частота процессора, ГГц']

tablet_colms_drop_list = ['Characteristics.Обязательные программы предустановлены',
 'Characteristics.Работа в режиме ожидания, ч',
 'Characteristics.Беспроводные интерфейсы',
 'Characteristics.Стандарты связи',
 'Characteristics.Форм-фактор SIM',
 'Characteristics.Модуль связи Bluetooth',
 'Characteristics.Модуль связи WiFi',
 'Characteristics.Навигация',
 'Characteristics.Разъемы',
 'Characteristics.Назначение слотов',
 'Characteristics.Работа в режиме телефона',
 'Characteristics.Встроенные датчики',
 'Characteristics.Функции камеры',
 'Characteristics.Особенности',
 'Characteristics.Макс. время работы (музыка),  ч',
 'Characteristics.Макс. время работы (видео),  ч',
 'Characteristics.Работа в режиме ожидания, ч',
 'Characteristics.Тип карты памяти',
 'Characteristics.Макс. объем карты памяти,  ГБ',
 'Characteristics.Число физических SIM-карт',
 'Characteristics.Цвет',
 'Characteristics.Срок службы, лет',
 'Characteristics.Гарантийный срок',
 'Characteristics.Гарантийный срок',
 'Characteristics.Модуль сотовой связи',
 'Characteristics.Число физических SIM-карт', 
 'Characteristics.Слот для карты памяти',
  

 ]

tablet_transformation_dict = {'Category':['category','object'],
 'Name':['name_card','object'],
 'Price':['price','numeric'],
 'Old Price':['price_old','numeric'],
 'Installment':['price_installment','numeric'],
 'Rating':['rating_card','float'],
 'Reviews':['reviews_card','int'],
 'Seller':['name_seller','object'],
 'Seller Rating':['rating_seller','float'],
 'URL':['url','object'],
 'Characteristics.Артикул':['article', 'int'],
 'Characteristics.Диагональ экрана, дюймы':['screen_diagonal', 'float'],
 'Characteristics.Оперативная память':['ram','float'],
 'Characteristics.Операционная система':['os','object'], #CATEGORY
 'Characteristics.Встроенная память,  ГБ':['internal_storage','int'],
 'Characteristics.Разрешение экрана':['screen_size','object'],
 'Characteristics.Процессор': ['cpu', 'object'],
 'Characteristics.Разрешение основной камеры, Мпикс':['main_camera','float'],
 'Characteristics.Технология матрицы':['matrix','object'],
 'Characteristics.Тип':['type_of_tablet','object'], #CATEGORY
 'Characteristics.Бренд':['brand','object'], #CATEGORY
 'Characteristics.Год анонсирования':['announcement_year','int'], #CATEGORY
 'Characteristics.Версия Android':['android_version','object'], #CATEGORY
 'Characteristics.Версия iOS':['ios_version', 'object'], #CATEGORY
 'Characteristics.Версия HarmonyOS': ['harmonyos_version','object'], #CATEGORY
 'Characteristics.Частота обновления экрана, Гц':['hz_screen','int'],
 'Characteristics.Плотность пикселей, ppi':['ppi','float'],
 'Characteristics.Бренд процессора':['processor_brand','object'], #CATEGORY
 'Characteristics.Бренд графического процессора':['brand_graphic_proccessor','object'], #CATEGORY
 'Characteristics.Число ядер процессора':['processor_cores','int'],
 'Characteristics.Частота процессора, ГГц':['ghz_processor','float'],
 'Characteristics.Видеопроцессор':['video_processor','object'],
 'Characteristics.Модуль сотовой связи':['cellular_network_module', 'object'],
 'Characteristics.Число физических SIM-карт':['count_sim','object'], 
 'Characteristics.Слот для карты памяти':['memory_card_slot','object'],
 'Characteristics.Разрешение фронтальной (селфи) камеры, Мпикс':['front_camera','float'],
 'Characteristics.Наличие клавиатуры':['keyboard','object'],
 'Characteristics.Основной материал корпуса':['case_material','object'],
 'Characteristics.Защита от влаги':['waterproof','object'],
 'Characteristics.Емкость аккумулятора, мАч':['battery_capacity','int'],
 'Characteristics.Аксессуары в комплекте':['accessories_included','object'],
 'Characteristics.Размеры, мм':['dimensions','object'],
 'Characteristics.Вес товара, г':['weight_g','float'],
 'Characteristics.Страна-изготовитель':['country_of_origin','object'], #CATEGORY

}

In [107]:
def convert_to_gb(df , work_col):
    s = df[work_col].astype(str).str.replace('Отсутствует', '', case=False).str.replace(',', '.')
    
    numbers = s.str.extract(r'(\d+\.?\d*)', expand=False).astype(float)
    
    is_mb = s.str.contains('МБ|MB', case=False, na=False)
    is_tb = s.str.contains('ТБ|TB', case=False, na=False)
    
    numbers = np.where(is_mb, numbers / 1024, numbers)
    numbers = np.where(is_tb, numbers * 1024, numbers)
    
    return numbers


def convert_hz_to_num(df,work_col):
 numbers = df[work_col].str.extract(r'(\d+\.?\d*)', expand=False)
 return numbers

def transform_dataframe(df, transformation_dict):
    df = df.copy()

    rename_map = {k: v[0] for k, v in transformation_dict.items()}
    df = df.rename(columns=rename_map)
    
    for old_name, info in transformation_dict.items():
        new_name = info[0]
        target_type = info[1]
        
        if new_name in df.columns:
            try:
                if target_type in ['numeric', 'float']:
                    df[new_name] = pd.to_numeric(df[new_name], errors='coerce')
                elif target_type == 'int':
                    df[new_name] = pd.to_numeric(df[new_name], errors='coerce').astype('Int64')
                elif target_type == 'object':
                    df[new_name] = df[new_name].astype('object') 
            except Exception as e:
                print(f"⚠️ Failed to convert '{new_name}': {e}")
    return df
    

def delete_unnecassary_rows_and_columns(df , threshold= 0.01):
 valid_ratio = df.notna().mean()
 bad_cols = valid_ratio[valid_ratio < threshold].index
 
 mask = df[bad_cols].isna().all(axis=1)
 df_cleaned = df[mask].drop(columns=bad_cols)
 return df_cleaned

In [108]:
df_tablet = delete_unnecassary_rows_and_columns(df = df_tablet)
df_tablet[tablet_handle_list[0]] = convert_to_gb(df_tablet, tablet_handle_list[0])
df_tablet[tablet_handle_list[1]] = df_tablet[tablet_handle_list[1]].astype(str).replace('Воротник для животных', np.nan)
df_tablet[tablet_handle_list[2]] = convert_hz_to_num(df_tablet, tablet_handle_list[2])
df_tablet[tablet_handle_list[3]] = pd.to_numeric(
    df_tablet[tablet_handle_list[3]]
    .astype(str)
    .str.replace(',', '.')
    .str.extract(r'(\d+\.?\d*)', expand=False), 
    errors='coerce'
)

In [109]:
df_tablet = df_tablet.drop(tablet_colms_drop_list, axis=1)
df_tablet = transform_dataframe(df_tablet, tablet_transformation_dict)

In [110]:
# print(df_tablet.columns)
print(df_tablet.info())
# df_tablet.sample(5)

<class 'pandas.core.frame.DataFrame'>
Index: 5553 entries, 0 to 5593
Data columns (total 41 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   category                  5553 non-null   object
 1   name_card                 5242 non-null   object
 2   price                     3862 non-null   float64
 3   price_old                 3862 non-null   float64
 4   price_installment         5221 non-null   float64
 5   rating_card               3437 non-null   float64
 6   reviews_card              3469 non-null   Int64
 7   name_seller               5242 non-null   object
 8   rating_seller             5185 non-null   float64
 9   url                       5553 non-null   object
 10  article                   5550 non-null   Int64
 11  screen_diagonal           5240 non-null   float64
 12  ram                       4729 non-null   float64
 13  os                        5273 non-null   object
 14  internal_storage          5447 non-null   Int64
 15  screen_size               5116 non-null   object
 16  cpu                       4003 non-null   object
 17  main_camera               4973 non-null   float64
 18  matrix                    4647 non-null   object
 19  type_of_tablet            5553 non-null   object
 20  brand                     1049 non-null   object
 21  announcement_year         4732 non-null   Int64
 22  android_version           4369 non-null   object
 23  hz_screen                 3831 non-null   Int64
 24  ppi                       2992 non-null   float64
 25  processor_brand           4915 non-null   object
 26  processor_cores           5167 non-null   Int64
 27  ghz_processor             4501 non-null   float64
 28  brand_graphic_proccessor  4045 non-null   object
 29  video_processor           2727 non-null   object
 30  front_camera              4865 non-null   float64
 31  keyboard                  3427 non-null   object
 32  case_material             4948 non-null   object
 33  waterproof                4070 non-null   object
 34  battery_capacity          5127 non-null   Int64
 35  accessories_included      2808 non-null   object
 36  dimensions                5075 non-null   object
 37  weight_g                  5202 non-null   float64
 38  country_of_origin         4726 non-null   object
 39  ios_version               379 non-null    object
 40  harmonyos_version         236 non-null    object
dtypes: Int64(7), float64(12), object(22)
memory usage: 1.8+ MB
None

In [112]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.expand_frame_repr', False)

# pd.reset_option('all')

In [113]:
df_smartphone = delete_unnecassary_rows_and_columns(df = df_smartphone)

In [114]:
print(df_smartphone.shape)
print(df_smartphone.columns.to_list())

(5382, 67)
['Category', 'Name', 'Price', 'Old Price', 'Installment', 'Rating', 'Reviews', 'Seller', 'Seller Rating', 'URL', 'Characteristics.Артикул', 'Characteristics.Обязательные программы предустановлены', 'Characteristics.Диагональ экрана, дюймы', 'Characteristics.Емкость аккумулятора, мАч', 'Characteristics.Процессор', 'Characteristics.Беспроводные интерфейсы', 'Characteristics.Разрешение экрана', 'Characteristics.Число ядер процессора', 'Characteristics.Оперативная память', 'Characteristics.Встроенная память', 'Characteristics.Разрешение основной камеры, Мпикс', 'Characteristics.Цвет', 'Characteristics.Тип', 'Characteristics.Версия смартфона', 'Characteristics.Восстановленный', 'Characteristics.Операционная система', 'Characteristics.Частота обновления экрана, Гц', 'Characteristics.Технология матрицы', 'Characteristics.Бренд процессора', 'Characteristics.Частота процессора, ГГц', 'Characteristics.Стандарты связи', 'Characteristics.Форм-фактор SIM', 'Characteristics.Поддержка eSim', 'Characteristics.Число физических SIM-карт', 'Characteristics.Модуль связи Bluetooth', 'Characteristics.Модуль связи WiFi', 'Characteristics.Аутентификация', 'Characteristics.Навигация', 'Characteristics.Интерфейсы', 'Characteristics.Слот для карты памяти', 'Characteristics.Функции камеры', 'Characteristics.Стабилизация', 'Characteristics.Количество основных камер', 'Characteristics.Разрешение фронтальной (селфи) камеры, Мпикс', 'Characteristics.Качество видео', 'Characteristics.Тип корпуса', 'Characteristics.Степень защиты', 'Characteristics.Функции зарядки', 'Characteristics.Размеры, мм', 'Characteristics.Вес товара, г', 'Characteristics.Гарантийный срок', 'Characteristics.Страна-изготовитель', 'Characteristics.Встроенные датчики', 'Characteristics.Основной материал корпуса', 'Characteristics.Тип карты памяти', 'Characteristics.Версия Android', 'Characteristics.Особенности', 'Characteristics.Бренд графического процессора', 'Characteristics.Видеопроцессор', 'Characteristics.Макс. объем карты памяти,  ГБ', 'Characteristics.Макс. скорость видеосъемки, кадр/с', 'Characteristics.Работа в режиме ожидания, ч', 'Characteristics.Время работы в режиме разговора, ч', 'Characteristics.Бренд', 'Characteristics.Срок службы, лет', 'Characteristics.Версия iOS', 'Characteristics.Версия HarmonyOS']

In [115]:
smartphone_drop_cols = ['Characteristics.Обязательные программы предустановлены',
 'Characteristics.Работа в режиме ожидания, ч',
 'Characteristics.Беспроводные интерфейсы',
 'Characteristics.Стандарты связи',
 'Characteristics.Форм-фактор SIM',
 'Characteristics.Модуль связи Bluetooth',
 'Characteristics.Модуль связи WiFi',
 'Characteristics.Навигация',
 'Characteristics.Встроенные датчики',
 'Characteristics.Функции камеры',
 'Characteristics.Особенности',
 'Characteristics.Работа в режиме ожидания, ч',
 'Characteristics.Тип карты памяти',
 'Characteristics.Макс. объем карты памяти,  ГБ',
 'Characteristics.Число физических SIM-карт',
 'Characteristics.Цвет',
 'Characteristics.Срок службы, лет',
 'Characteristics.Гарантийный срок',
 'Characteristics.Гарантийный срок',
 'Characteristics.Число физических SIM-карт', 
 'Characteristics.Слот для карты памяти',
 'Characteristics.Время работы в режиме разговора, ч',
 'Characteristics.Функции зарядки',
 'Characteristics.Качество видео',
 'Characteristics.Количество основных камер',
 'Characteristics.Стабилизация',
 'Characteristics.Интерфейсы',
 'Characteristics.Аутентификация',
 'Characteristics.Восстановленный',
 'Characteristics.Версия смартфона',
 'Characteristics.Тип'
]

smartphone_transform = {'Category':['category','object'],
 'Name':['name_card','object'],
 'Price':['price','numeric'],
 'Old Price':['price_old','numeric'],
 'Installment':['price_installment','numeric'],
 'Rating':['rating_card','float'],
 'Reviews':['reviews_card','int'],
 'Seller':['name_seller','object'],
 'Seller Rating':['rating_seller','float'],
 'URL':['url','object'],
 'Characteristics.Артикул':['article', 'int'],
 'Characteristics.Диагональ экрана, дюймы':['screen_diagonal', 'float'],
 'Characteristics.Оперативная память':['ram','float'],
 'Characteristics.Операционная система':['os','object'], #CATEGORY
 'Characteristics.Встроенная память,  ГБ':['internal_storage','int'],
 'Characteristics.Разрешение экрана':['screen_size','object'],
 'Characteristics.Процессор': ['cpu', 'object'],
 'Characteristics.Разрешение основной камеры, Мпикс':['main_camera','float'],
 'Characteristics.Технология матрицы':['matrix','object'],
 'Characteristics.Бренд':['brand','object'], #CATEGORY
 'Characteristics.Год анонсирования':['announcement_year','int'], #CATEGORY
 'Characteristics.Версия Android':['android_version','object'], #CATEGORY
 'Characteristics.Версия iOS':['ios_version', 'object'], #CATEGORY
 'Characteristics.Версия HarmonyOS': ['harmonyos_version','object'], #CATEGORY
 'Characteristics.Частота обновления экрана, Гц':['hz_screen','int'],
 'Characteristics.Плотность пикселей, ppi':['ppi','float'],
 'Characteristics.Бренд процессора':['processor_brand','object'], #CATEGORY
 'Characteristics.Бренд графического процессора':['brand_graphic_proccessor','object'], #CATEGORY
 'Characteristics.Число ядер процессора':['processor_cores','int'],
 'Characteristics.Частота процессора, ГГц':['ghz_processor','float'],
 'Characteristics.Видеопроцессор':['video_processor','object'],
 'Characteristics.Модуль сотовой связи':['cellular_network_module', 'object'],
 'Characteristics.Число физических SIM-карт':['count_sim','object'], 
 'Characteristics.Слот для карты памяти':['memory_card_slot','object'],
 'Characteristics.Разрешение фронтальной (селфи) камеры, Мпикс':['front_camera','float'],
 'Characteristics.Наличие клавиатуры':['keyboard','object'],
 'Characteristics.Основной материал корпуса':['case_material','object'],
 'Characteristics.Защита от влаги':['waterproof','object'],
 'Characteristics.Емкость аккумулятора, мАч':['battery_capacity','int'],
 'Characteristics.Аксессуары в комплекте':['accessories_included','object'],
 'Characteristics.Размеры, мм':['dimensions','object'],
 'Characteristics.Страна-изготовитель':['country_of_origin','object'], #CATEGORY
 'Characteristics.Макс. скорость видеосъемки, кадр/с':['max_fps_video' , 'int'],
 'Characteristics.Вес товара, г':['weight_g','float'],
 'Characteristics.Степень защиты':['degree_of_protect', 'object'],
 'Characteristics.Тип корпуса':['type_of_frame', 'object'], #CATEGORY
 'Characteristics.Поддержка eSim':['e_sim','object'], #CATEGORY
 

}


smartphone_repl = [
 'Characteristics.Оперативная память',
 'Characteristics.Встроенная память',
 'Characteristics.Частота обновления экрана, Гц', 
]

In [116]:
df_smartphone[smartphone_repl[1]] = convert_to_gb(df_smartphone, smartphone_repl[1])
df_smartphone[smartphone_repl[0]] = convert_to_gb(df_smartphone, smartphone_repl[0])
df_smartphone[smartphone_repl[2]] = convert_hz_to_num(df_smartphone, smartphone_repl[2])

In [117]:
df_smartphone = df_smartphone.drop(smartphone_drop_cols, axis=1)
df_smartphone = transform_dataframe(df_smartphone, smartphone_transform)

In [118]:
for col in df_smartphone.columns:
 a = df_smartphone[col].unique()
 print("================================================")
 print('')
 print(col)
 print('')
 print(a)

================================================

category

['smartphones']
================================================

name_card

['Xiaomi Смартфон Xiaomi Redmi Note 14 Pro+ 5G Ростест (EAC) 8/256 ГБ, светло-желтый'
 'Смартфон A16 Pro Ростест (EAC) 16/1 ТБ, серый' None ...
 'Смартфон Reno14 F Ростест (EAC) 16/1 ТБ, белый'
 'Honor Смартфон X9d Ростест (EAC) 8/256 ГБ, зеленый'
 'Xiaomi Смартфон Redmi 15 Titan Gray Ростест (EAC) 6/128 ГБ, серый']
================================================

price

[216456.  54016.     nan ...  51590. 202203.  89962.]
================================================

price_old

[542517. 440665.     nan ... 858021. 198699. 141049.]
================================================

price_installment

[18038.  4502.    nan ...  2253. 12606.  7497.]
================================================

rating_card

[4.8 5.  nan 4.7 4.3 4.6 4.9 3.8 4.5 4.1 4.4 4.2 3.6 3.9 4.  3.  3.2 2.5
 3.7 2.9 3.5 2.  2.7 3.3 3.1 1.  3.4 2.6 1.8 1.2 2.2]
================================================

reviews_card

<IntegerArray>
[  322,    29,  <NA>,     9,    63,    80,   111,    11,    48,    21,
 ...
 11194,  3449,   347,  2965,   312,   196,  1021,  3487,  1262,  1428]
Length: 524, dtype: Int64
================================================

name_seller

['SmartPhone' 'AMG' None 'Teleflow' 'opt. marina' 'Buyon'
 'Магазин 3854971' 'Yll4' 'Фирменный магазин T...' 'Smart store'
 'Sotomania' 'ZUNYI Pura Store' 'Appel' 'PhoneStore' 'Позитроника'
 'Global Superstores ...' 'Ozon Россия' 'Флагманский магазин' 'Хеди'
 'МСота' 'MI Магазин' 'pupu' 'F-Store' 'Летний информационн...'
 'MICS Distribution' 'VEDYARTI' 'I7-STORE' 'Магазин 3689280'
 'NexusGlow Store' 'Коммуникации' 'Абсолют Трейд' 'Фирменный магазин H...'
 'PAGRAER TrendSpace' 'Yuuoio5' 'FonLine' 'Vivo Official Store' 'dnfieklg'
 'RTG' 'PAGRAER Digital Vau...' 'Blue Sky элeктроник...'
 'PhotonBoost Store' 'Formey Store' 'E-lectronix' 'Eurasian Phone'
 'Mobilny Mir (Мобиль...' 'Xie Phone' 'iQOO Official Store' 'AppClinic2'
 'Цифровой дизайн' 'PAGRAER Alpha' 'AppClinic' 'CyberZarya'
 'PAGRAER Sync Zone' 'Ozon Казахстан' 'RBT' 'MNJ889' 'MaxTech Store'
 'МОЙ ТЕЛЕФОН' 'OOO SMARTSTORE' 'Red_Market' 'XCOM-SHOP' 'iouio 31'
 'hassenda' 'is.mall' 'Мир электроники' 'Grontor' 'Технология Сянхай(1...'
 'NOAH' 'wewi' 'PAGRAER Future Tech' 'nagadh' 'Aina_market' 'SmartArea'
 'AQE334' 'РОМNBPULS' 'Aoaishe' 'ИнноваСтрим' 'PAGRAER NexGen Store'
 'ZHII10' 'МЕГАphone' 'SkyStore' 'Бизнес Оборудование' 'Reno.Россия'
 'diMoll' 'ocean' 'Koi Store' 'Smartsell' 'Радуга' 'Seferyan61'
 'Магазин-shop' 'SAMSUNG STORE' 'GigaMarkt' 'Smart Store' 'HNHB07b'
 'ИП Мантыев Василий ...' 'Адаптер' 'Digital World' 'ЦифраМаг'
 'Телеком Маркет' 'YZ Store' '"АЛЬФА ЭЛЕКТРОНИКА"'
 'ИП Хаидов Юнус Абуеви...' 'QK02' 'TUTU' 'HNHB07a' 'Modern Comfort'
 'AppleTechnology' 'ELECTRONIC ECOSYSTE...' 'Air Store' 'Mega Store'
 'Fashion Store' 'ZUNYI PRO Store' 'Московский Мобильный ...' 'Zeus tech'
 'Молния Электроника(...' 'Wu MI/3' 'TechnoLife' 'ZUNYI  Y Store'
 'Gold Gadgets' 'Zone Store' 'palinda' 'Техно Восток' 'E-BONUS'
 'Эльдорадо' 'UNIERSAR TIGER' 'BassBoomRu' '"ТвойМаркет Электро...'
 'М.Видео' 'vzAS14-3' 'MobileOne' 'duoduomi' 'Infinix Store'
 'ООО "МАГ ДЕВАЙС"' 'МегаФон' 'ПЛЮС Store' 'GSM BUTIK' 'Цифровой Остров'
 'ZUNYI XS Store' 'Fire Store' 'ТехноМаркет' 'dfkgljelr'
 'Магазин беспошлинной ...' 'PAGRAER Byte Hub' 'ZUNYI VIP Store'
 'ЭкспертТехники' 'Скидка Phone HM2' 'PAGRAER ElectroSpace' 'Smart#Fon'
 'Подсолнечные Коммун...' 'Yudu TECH' 'TECNO STORE' 'Магазин 27'
 'Флагманский магазин...' 'SmartX' 'ООО "КОНТЕКСТ"' 'SmartSpace.shop'
 'ZUNYI M Store' 'ZUNYI Zero Store' 'JXMM 29' 'Uncle Jops'
 'Чжидатехнолодж Трейд' 'Официальный магазин' 'Lime Store' 'dnsfile'
 'Мир электроники Маг...' 'Фирменный магазин S...' 'ArtHouse3D'
 'Fox Mobile 1' 'Annie Phone' 'ZUNYI Phones Store'
 'Jianyi Digital Co.,...' 'ASSSA32' 'Smart touch' 'DHS Shop' 'QQFC2-4'
 'LQ Store' 'renyi' 'Магазин 28' 'Technology Store'
 'Золотая Гора Электр...' 'Тилекович Цифровой ...' 'CommBox' 'ЗЕОН'
 'Bobo Phone' 'ИП Кулпеишова' 'Магазин 3913761' 'Магазин 3671106'
 'Vigran Store' 'Сесилия 1997' 'PAGRAER Smart Sourc...' 'WEN Phone'
 'Poco RUS' 'TR Store' 'ZUNYI POP Store' 'TechZone' 'ИП Морозова С.О.'
 'Магазин 3' 'Mi_mobile' 'Google Store' 'SmartPro' 'NOVEX' 'DigitSmart'
 'Хочу смартфон!' 'fufu' 'ElectroWave' 'MINGXI' 'PAGRAER Digital Sph...'
 'NICE' 'Сладкий мир' 'Китайский умный маг...' 'ООО "ОТСЕТИ.РУ"'
 'Phone Marke' 'Магазин смартфонов по...' 'Импульс Про' 'Mago' 'lirngde'
 'Extreme-Tel' '16BB' 'OOO PLANSHETIVSEM' 'Smart Market' 'Один нож'
 'PAGRAER Premium Exp...' 'Тайцзи' 'Ice Blue' 'Wuhu Xingfang Tradi...'
 'Мир гаджетов' 'LDMLIKE' 'СанЖан (SanZhan)' 'Top Store' 'AG'
 'Умная Техника' 'ZUNYI Spark Store' 'White Store' 'The Phone Lab'
 'QIANDUODUO' 'Darinka Brand Store' 'Gadget_Pro' 'Трейд Трекер' 'Nology'
 'DiStore' 'Xiaomi - фирменный ...' 'Smart Hub' 'Брендовый магазин PAG...'
 'УмныйМир' 'SMARTZONE Store' 'FATI market' 'Xiaodao Brothers' 'Duoqin'
 'Samsung Брендовый М...' 'XIAOXINGXING' 'Federal Express' 'Zen Mobile'
 'Потерянный рай' 'T2' 'Digixel' 'Wzxxc14-4' 'Магия качества' 'Акма'
 '"Смартфоны / Планше...' 'Вспышка звезды' 'Point' 'iVika'
 'DuMeiLongevity & Peac...' 'wawys' 'PAGRAER Device Univ...'
 'REDMAGIC Official S...' 'Asan shop' 'ZUNYI Premium Store' 'HYF990'
 'MiFans Store' 'Магазин надежды' 'X Store' 'qin' 'fghlrt'
 'Takephone Россия' 'OOO PHONEPRO' 'Phone World Store' 'Piter-Tel'
 'MI SHOP' 'LITE-MOBILE' 'POCO HOME' 'ydgncd' 'Цифровой Зверь'
 'Виктория магазин' 'TopComputer' 'Цифровой магазин' 'kdngie' 'Tenco'
 'Официальный Магазин...' 'QQFC2-5' 'zhenengshouji' 'Мой Смарт'
 'Lia Phone' 'SPARK Store' 'Vсмартфоне' 'ELARI Официальный м...' 'Airwill'
 'MobiX' 'HypeStore' 'shiyi' 'Опт и розница' 'DV-Shop' 'Мобильный Мир'
 'Ice Tech' 'ноутбук' 'Интернет-магазин Al...' '1к' 'СмартТехно'
 'VoltGear' 'TopGadjet' 'POCO Store' 'ПЛК' 'Magic Store' 'Мегаполис'
 'Silk Store' '7II' 'One step before' 'ТехСферум' 'Нокиа.Россия'
 'Best Buy' 'DigiMart Store' 'Poco Tech.' 'Мир технологий' 'КиберМаг'
 'KXTX' 'ВОСТОЧНЫЙ АПЕКС' 'Фотосклад' 'meiejgdfmdn' 'ВоксПад'
 'Авторизованный парт...' 'SANTIN' 'СТАРКАД' 'Dixmobile' 'Royuoo'
 'Умные цены на смартфо...' 'Science Technology Be...' 'Телефон для Семьи'
 'Qin Global store' 'Smartphone stores' 'BST' 'Доступная электроника'
 'Mi Future Hub' 'Золотой Гаджет' 'ТехноСити' 'КомпьютерМаркет' 'KFC'
 'chanson' 'магазин мобильных тел...' 'LITONG' 'СмартМаркет' 'POCO'
 'РУСЛАН' 'T&H Kids' 'QC-Smart' 'MI Tech.' 'Классный цифровой' 'ZY STORE'
 'Марс Электроникс(3)' 'PAGRAER Forge' 'MI Smart' 'Дом Технологий'
 'AFITRON' 'Логистик-Сервис' 'Магазин Xiaomi' 'Gl26AP17' 'ER Store'
 'Aplus' 'Mi Smart Global Store' 'Go Gadget' 'Мирный смертный'
 'Восточный универмаг' 'Юг Ритейл' 'Т-СМАРТ' 'first smart' 'РУУСА'
 'СуперВыгода Телефон P...' 'Крепость Смарт' 'FutureTech (ФьючеТе...'
 'Nasty_Fox' 'Nano Цифровой магазин' 'VORTEX' 'Диджитал Стандарт'
 'Глобальный шопинг' 'Honor China' 'Technosan' 'Attract Shop'
 'отборный-Ми-магазин..' 'Бренд телефон' 'LUCKY' 'PhoneToBe' 'iBest'
 'Mijia' 'EFFIA' 'Lasa_store' 'ТехноГрад' 'RIKOR' 'БЫСТРОТЕХ'
 'Магазин мобильных тел...' 'PAGRAER NexGen Stor...' 'ПульсБит'
 'PAGRAER Inn Station' 'ИП Мантыев Василий Чо...' 'PAGRAER ElectroSpac...'
 'Телефон гипермаркета ...' 'Высококачественный ...' 'СмартТеле'
 '«ТехноТОП»' '"Интернет Система"' 'E-shop' 'Nova Mobiles' 'YMT4-3'
 'Цифрум' 'SORTSTOCK' 'Trendy Store' 'ХайФренд(Hi.Friend)' 'ApMi Shop'
 'Магазин 3849407' 'Магазин 3854211' 'Киоск телефонов' 'Cozy Vibe'
 'Vikequ' 'Надёжно и точка.' 'Lucky_Shop' 'iG-Store' 'СМАРТ-РУ'
 'wisdom-shop' 'Sold-Out' 'Trustphone' 'Good quality phone' 'Chuang Bo'
 'Myth Tech' 'Океанский магазин' 'Novo Store' 'realme' 'смартфон'
 'niuyihgb' 'Цифровой дом' 'Go Gadgets' 'РСТ Store' 'Feixinxk' 'HCH Store'
 'Varik' 'Яюань Торговля' 'ROCKET' 'ТекБридж' 'Zhoujia']
================================================

rating_seller

[4.9 4.5 nan 4.3 4.8 4.6 5.  4.7 4.1 4.4 4.2 3.9 3.5 4.  3.8 3.7 3.3 3.6]
================================================

url

['https://www.ozon.kz/product/xiaomi-smartfon-xiaomi-redmi-note-14-pro-5g-rostest-eac-8-256-gb-svetlo-zheltyy-3469361238/'
 'https://www.ozon.kz/product/smartfon-a16-pro-rostest-eac-16-1-tb-seryy-3689839206/'
 'https://www.ozon.kz/product/redmi-smartfon-8-256-gb-chernyy-3198103504/'
 ...
 'https://www.ozon.kz/product/honor-smartfon-x9d-rostest-eac-8-256-gb-zelenyy-2916989022/'
 'https://www.ozon.kz/product/huawei-smartfon-nova-13-pro-rostest-eac-12-512-gb-chernyy-1841845756/'
 'https://www.ozon.kz/product/xiaomi-smartfon-redmi-15-titan-gray-rostest-eac-6-128-gb-seryy-2855486570/']
================================================

article

<IntegerArray>
[3469361238, 3689839206, 3198103504, 3323519430, 2396422064, 2576111666,
 3583291489, 3823185040, 3622371532, 2400207473,
 ...
 2745701490, 3642992204, 3132456484, 3536697917, 2946032449, 3280226167,
 3759398594, 2916989022, 1841845756, 2855486570]
Length: 5374, dtype: Int64
================================================

screen_diagonal

[ 6.67   6.8    6.79   6.86   6.88     nan  7.3    6.2    7.88   6.77
  6.1    6.78   6.7    6.72   6.9   10.     6.83   6.5    6.58   6.3
  6.74   6.71   5.8    6.68   7.2    6.85   6.6    4.5    6.55   6.43
  7.8    6.36   5.4    4.     5.86   6.31   6.52   6.53   6.4    3.
  6.59   6.57   6.22   6.76   6.75   6.81   8.     6.     6.21   6.56
  4.6    6.47   5.45   6.73   4.7    6.28   6.15   6.61   5.     5.7
  3.5    2.95   7.6    6.621  5.99   6.26   6.611  3.75   3.8    2.8
  5.84   2.5    6.95   5.3    1.8    5.05   5.93   3.54   7.93   6.65
  6.35   2.4    4.3    5.81   6.561  3.74   7.     3.7    1.77   5.42
  6.822  5.2    6.745  5.6  ]
================================================

battery_capacity

<IntegerArray>
[ 5110,  8000,  5030,  4780,  5160,  <NA>,  6000,  7000,  4230,  8800,
 ...
  2500, 11800,  4860,  5825,  2200,  6210,  3582,  5850,  6180, 15080]
Length: 170, dtype: Int64
================================================

cpu

['Snapdragon 7s Gen3' 'Dimensity 9300 Plus' nan 'Snapdragon 8 Gen3'
 'Helio G81' 'Snapdragon 7s Gen4' 'Snapdragon 450'
 'Snapdragon 8 Gen3 Leading Version' 'A17 Pro' 'Helio G200'
 'Snapdragon 778G Plus' 'T7250' 'Helio G80' 'Helio G92 Max'
 'Helio G100 Ultra' 'Kirin 980' 'G99 Ultimate' 'Helio P35' 'Helio G96'
 'Helio G99 Ultimate' 'Kirin 710' 'Exynos 1480' 'Snapdragon 8 Elite Gen5'
 'Helio P22' 'Dimensity 9500' 'A11 Bionic' 'Snapdragon 685' 'Helio P60'
 'Dimensity 8400 Ultra' 'Snapdragon 7 Gen3' 'Snapdragon 8 Gen2'
 'Helio G81 Ultra' 'Snapdragon 8s Gen4' 'A10 Fusion' 'MT6762R'
 'A15 Bionic' 'Dimensity 7300' 'A14 Bionic' 'Snapdragon 680'
 'Helio G99 Ultra' 'MT6739' 'Helio G88' 'Snapdragon 8 Gen5' 'MT8788'
 'Helio P25' 'A13 Bionic' 'Snapdragon 662' 'Dimensity 7360 Turbo'
 'Helio G200 Ultimate' 'Kirin 9020' 'Exynos 7884' 'T610' 'A16 Bionic'
 'Snapdragon 750G' 'Tiger T612' 'Exynos 2400' 'Helio G100 Ultimate'
 'Tiger T606' 'Helio G85' 'Dimensity 7400 Ultra' 'Dimensity 8500 Ultra'
 'Dimensity 9400' 'Helio G200 Ultra' 'Snapdragon 778G' 'Exynos 9820'
 'Dimensity 7100' 'A12 Bionic' 'Exynos 2600' 'Helio G99' 'Helio G95'
 'Dimensity 8350 Ultimate' 'MT6580' 'Dimensity 7300 Max 5G' 'Cortex-A53'
 'Helio G90T' 'Snapdragon 7 Gen1' 'Snapdragon 7s Gen2' 'Exynos 2200'
 'Snapdragon 8 Elite for Galaxy' 'Snapdragon 8 Plus Gen1' 'Tiger T616'
 'T606' 'Exynos 1580' 'Helio G100' 'Dimensity 1080' 'Tiger T615'
 'Dimensity 7050' 'Snapdragon 6s 4G Gen2' 'Exynos 2500' 'Snapdragon 855'
 'Dimensity 700' 'Snapdragon 888' 'Snapdragon 8 Gen1' 'Helio G35'
 'Dimensity 7300 Ultimate' 'Snapdragon 6 Gen3' 'Snapdragon 8s Gen3'
 'Dimensity 8200 Ultra' 'T8100' 'Snapdragon 480' 'A19 Pro'
 'Dimensity 6400 Max 5G' 'Exynos 1680' 'Dimensity 7360' 'T612'
 'Snapdragon 6 Gen4' 'Exynos 1280' 'Helio P65' 'Tensor G4' 'MT6755'
 'Helio G91 Ultra' 'Helio G81 Ultimate' 'Snapdragon 695'
 'Dimensity 1000 Plus' 'Helio A22' 'Helio G36' 'Kirin 9010S' 'Helio P23'
 'Kirin 8020' 'MT6752' 'Exynos 980' 'Exynos 1380' 'Snapdragon 865'
 'MT6580М' 'Dimensity 7400-Turbo' 'Snapdragon 8 Elite Gen5 for Galaxy'
 'MT8168' 'Dimensity 7400' 'Dimensity 8050' 'Kirin T91' 'MT6737'
 'Exynos 850' 'Helio G25' 'Dimensity 8200 Ultimate' 'Core i7-1165G7'
 'Snapdragon 860' 'Snapdragon 730' 'MT6739WW' 'Dimensity 8350' 'SC9863A'
 'Tensor G5' 'Dimensity 920' 'Snapdragon 6s 4G Gen1' 'Snapdragon 675'
 'Kirin 8000' 'T765' 'Helio A25' 'Kirin 970' 'Exynos 7904' 'Kirin 710A'
 'A18 Bionic' 'Snapdragon 425' 'Dimensity 7300 Plus 5G' 'Snapdragon 660'
 'Dimensity 7100 Elite' 'Kirin 710F' 'Dimensity 7020'
 'Dimensity 7025 Ultra' 'Helio G37' 'Helio G91' 'Snapdragon 720G' 'MT6732'
 'Snapdragon 8 Elite' 'Exynos 990' 'Snapdragon 732G' 'MT8765'
 'Dimensity 9400 Plus' 'A18 Pro Bionic' 'Dimensity 7300 Pro 5G'
 'Kirin 659' 'Helio P90' 'Dimensity 1000' 'Kirin 9010' 'Kirin 810'
 'Dimensity 720' 'Snapdragon 7 Plus Gen2' 'A12Z Bionic' 'MT6735' 'MT6765'
 'Snapdragon 460' 'A18' 'A19' 'Snapdragon 630' 'Snapdragon 870'
 'Exynos 1330' 'Dimensity 8020' 'Tiger T603' 'Snapdragon 665'
 'Snapdragon 7 Gen4' 'Dimensity 6020' 'Dimensity 9200 Plus' 'T7225'
 'Snapdragon 8 Plus Gen2' 'Snapdragon 6 Gen1' 'Dimensity 6080 5G'
 'Dimensity 8300 Ultra' 'Dimensity 7300 Ultra' 'MT6737H' 'Helio A20'
 'Dimensity 8100' 'Dimensity 6100 Plus' 'Snapdragon 780G' 'MT6735M'
 'Snapdragon 7 Plus Gen3' 'Dimensity 7200 Ultra' 'Dimensity 800U'
 'MT8163V/A' 'Dimensity 8300' 'MT6737WT' 'Exynos 2400e' 'Snapdragon 765G'
 'Snapdragon 765' 'Tensor G3' 'Snapdragon 439' 'Snapdragon 835'
 'Dimensity 6300' 'MT6582' 'Exynos 2100' 'MTD7300' 'Tiger T820'
 'Dimensity 7400X' 'Core i7-1065G7' 'A100' 'T770' 'Snapdragon 690'
 'Tensor' 'Dimensity 9500s' 'Dimensity 1100']
================================================

screen_size

['2712x1220' '3200x2400' '2400x1080' '2700x1224' '1640x720' nan
 '1920x1080' '3120x1440' '1520x720' '1600x720' '1604x720' '2392x1080'
 '2556x1179' '2300x1080' '2048x1080' '2340x1080' '3200x1440' '2772x1280'
 '1080x2408' '2436x1080' '2560x1440' '2720x1224' '2808×1256' '2436x1125'
 '1608x720' '3168x1440' '2760x1256' '2160x1080' '3200x2136' '2800x1260'
 '1334x750' '2532x1170' '1612x720' '1200x2608' '2640x1200' '2644x1208'
 '1560x720' '1650x720' '2280x1080' '2796x1290' '3440x1440' '480x854'
 '1220x2700' '1080x2340' '1792x828' '2756x1268' '1320x2868' '1316x2832'
 '3040x1440' '1080x540' '2772x1240' '2776x1224' '3216x1440' '960x480'
 '2772x1272' '2460x1080' '1220x2712' '2184x1968' '2412x1080' '2750x1236'
 '384x854' '2800x1280' '1600x900 HD+' '1570x720' '2520x1080' '2344x1080'
 '2640x1080' '1440x720' '1024x576' '240x400' '2622x1206' '2372x1080'
 '1620x1080' '2868x1320' '1366x768' '2560x1080' '1610x720' '3088x1440'
 '2670x1200' '1344x2992' '1440x1440' '1280x480' '2856x1320' '2736x1264'
 '2312x1080' '3000x1876' '1800x1200' '2856x1280' '1920x720' '282x470'
 '960x640' '640x480' '2750x1260' '2176x1812' '1680x720' '2700x1220'
 '2560x2048' '1872x1404' '3200x2000' '2412x1084' '2240x1080' '1200x2600'
 '2848x1276' '320x240' '1920x1440' '2424x1080' '2232x1080' '2800x1272'
 '1920x1200' '240x120' '2160x1440' '2664x1200' '1080x720' '2844x1260'
 '2376x1080' '2232x3184' '3840x2160' '128x160' '2688x1216' '432x514'
 '2778x1284' '120x160' '2388x1080' '240x286' '2440x2240' '3120x2080'
 '1280x720' '1280x2800' '3840x2400' '1544x720' '2560x1600' '432x240'
 '540x1200' '440x696' '1860x2480' '2400x480' '450x450' '1280x800'
 '2800x1264' '2800x1980' '192x490' '768x1280' '1500x720' '1156x2510'
 '72x144' '5760x2880']
================================================

processor_cores

<IntegerArray>
[8, 10, <NA>, 2, 6, 4, 1, 3, 9, 12, 18, 16]
Length: 12, dtype: Int64
================================================

ram

[ 8.  16.  12.   6.   nan 22.   4.   3.   2.  24.   1.  10.   1.5]
================================================

Characteristics.Встроенная память

[2.560e+02 1.024e+03 5.120e+02       nan 2.048e+03 1.280e+02 6.400e+01
 3.200e+01 1.600e+01 2.000e+00 4.000e+00 8.000e+00]
================================================

main_camera

[200.  108.   50.    nan  13.   48.    8.   40.   64.   16.   32.   25.
  12.   72.    5.  135.   20.   21.    2.   24.  100.   26.   52.   54.
  30.   10.    0.8   3.   68.   23.   23.8  80.    0.3  12.2  19.  107.
 103.  106.   36. ]
================================================

os

['Android' nan 'iOS' 'EMUI 15' 'Другая' 'EMUI 14' 'EMUI 14.2' 'Windows']
================================================

hz_screen

<IntegerArray>
[120, 90, <NA>, 144, 60, 110, 100, 140, 165, 160]
Length: 10, dtype: Int64
================================================

matrix

['AMOLED' 'IPS' nan 'LTPS' 'IPS HD+' 'LCD' 'OLED' 'PLS' 'Super AMOLED'
 'Super Retina XDR' 'LTPO AMOLED' 'E-ink Triton' 'TFT' 'Dynamic AMOLED 2X'
 'E-ink' 'AAS' 'E-ink HD' 'TFT LCD' 'P-OLED' 'Super IPS' 'Super IPS LCD2'
 'A-MVA' 'ADS' 'MIP' 'LTPS AMOLED' 'LTPO OLED' 'AMVA+' 'Super AMOLED Plus'
 'Графический LCD' 'Full HD Super AMOLED' 'True HD IPS+' 'SuperLCD'
 'Super Clear LCD' 'QLED' 'E-ink HD Carta' 'E-Ink Print Color'
 'E-ink Pearl' 'CSTN' 'Ultra AMOLED' 'E-ink Carta' 'Retina IPS' 'TN']
================================================

processor_brand

['Qualcomm' 'MediaTek' nan 'AMD' 'Apple' 'Unisoc' 'HiSilicon' 'Samsung'
 'Kirin' 'ARM' 'Google' 'Intel' 'Spreadtrum' 'Allwinner']
================================================

ghz_processor

[2.50e+00 3.40e+00 2.00e+00 3.30e+00      nan 3.00e+00 2.20e+00 2.40e+00
 1.80e+00 2.60e+00 2.70e+00 2.30e+00 2.05e+00 4.50e+00 2.75e+00 4.60e+00
 2.10e+00 2.80e+00 3.25e+00 2.63e+00 3.20e+00 3.10e+00 2.34e+00 2.99e+00
 2.66e+00 1.50e+00 3.50e+00 1.60e+00 3.46e+00 2.65e+00 3.73e+00 4.00e+00
 3.80e+00 3.32e+00 3.23e+00 3.35e+00 1.30e+00 3.19e+00 2.90e+00 1.40e+00
 2.84e+00 3.21e+00 4.21e+00 3.36e+00 4.70e+00 3.60e+00 4.20e+00 2.96e+00
 1.82e+00 3.78e+00 4.47e+00 4.32e+00 2.36e+00 3.70e+00 3.89e+00 2.27e+00
 4.61e+00 3.90e+00 5.00e+00 4.30e+00 3.62e+00 2.85e+00 1.90e+00 4.26e+00
 1.95e+00 2.45e+00 1.70e+00 1.60e+03 2.23e+00 4.40e+00 3.41e+00]
================================================

e_sim

['eSIM+SIM' 'SIM (без eSIM)' nan 'только eSIM']
================================================

front_camera

[20.   50.   13.   32.     nan 65.    8.   12.   24.    7.   48.   16.
  5.   38.   64.   45.    0.3  60.   10.   18.    2.   25.   40.   42.
 10.5   2.4   0.8  15.    0.08 30.   31.96  2.2  49.   21.   36.    0.9
 63.  ]
================================================

type_of_frame

['Моноблок' 'Складной' nan]
================================================

degree_of_protect

['IP68' 'IP45' 'IP53' nan 'IP66' 'IP64' 'IP59' 'IP68, IP69K' 'IP69' 'IP10'
 'IP54' 'IP60' 'IP67' 'IP68, IP69K, IP69' 'IP58' 'IP68, IP69' 'IP50'
 'IP55' 'IP65' 'IP57' 'IP12' 'IP69, IP69K' 'IPX5' 'IP11'
 'IP69K, IP69, IP68' 'IP63' 'IP52' 'IP69K' 'IP69, IP68' 'IP31'
 'IP69K, IP68' 'IP48' 'IP46' 'IP00' 'IP68, IP66, IP69, IP69K' 'IP73'
 'IPX8' 'IP66, IP68, IP69' 'IP38' 'IP56' 'IP13' 'IP52, IPX2'
 'IP68, IP69, IP69K' 'IP20' 'IPX6' 'IPX6, IPX8, IPX9' 'IPX12' 'IPX4'
 'IP18' 'IP42' 'IP17' 'IP62' 'IP64, IP65' 'IP66, IP68, IP69K, IP69'
 'IP67, IP68' 'IP44' 'IP40, IP55' 'IP16' 'IP54, IP65' 'IP35' 'IPX2'
 'IP22S' 'IP23' 'IP69, IP68, IP66' 'IP21' 'IP30' 'IP14' 'IP51'
 'IP69, IP66, IP68, IP69K' 'IP66, IP68, IP69, IP69K' 'IP43' 'IP25' 'IPX9']
================================================

dimensions

['162.53х74.67х8.85' '155*74*8.4' '168.6 x 76.3 x 8.3' ... '161x75x8'
 '167.2*76.6*7.8' '7.8x16.17x8.2 ']
================================================

weight_g

[205.13 200.   205.   192.   211.      nan 400.   162.   196.   528.
 220.   187.   170.   178.   188.   184.   165.   207.   324.   150.
 438.   179.   193.   225.   198.   219.   154.   377.   174.   204.
 210.   186.   157.   115.   195.   194.   185.   199.   206.   203.
 300.   493.   232.   175.   160.   180.   202.   189.   191.   292.
 214.   156.   208.   169.   290.   364.   378.   240.    65.   190.

In [119]:
print(df_laptop.shape)
print(df_laptop.columns.to_list())

(5411, 228)
['Category', 'Name', 'Price', 'Old Price', 'Installment', 'Rating', 'Reviews', 'Seller', 'Seller Rating', 'URL', 'Characteristics.Артикул', 'Characteristics.Обязательные программы предустановлены', 'Characteristics.Процессор', 'Characteristics.Общий объем SSD, ГБ', 'Characteristics.Видеокарта', 'Characteristics.Операционная система', 'Characteristics.Диагональ экрана, дюймы', 'Characteristics.Оперативная память', 'Characteristics.Время автономной работы, ч', 'Characteristics.Вес, кг', 'Characteristics.Технология матрицы', 'Characteristics.Тип памяти', 'Characteristics.Модуль связи Bluetooth', 'Characteristics.Материал корпуса', 'Characteristics.Цвет', 'Characteristics.Форм-фактор ноутбука', 'Characteristics.Версия Windows', 'Characteristics.Модель процессора', 'Characteristics.Бренд процессора', 'Characteristics.Частота процессора, ГГц', 'Characteristics.Число ядер процессора', 'Characteristics.Форм-фактор SSD', 'Characteristics.Разрешение экрана', 'Characteristics.Яркость, кд/м2', 'Characteristics.Сенсорный экран', 'Characteristics.Интерфейсы и разъемы', 'Characteristics.Число портов HDMI', 'Characteristics.Число портов USB 2.0', 'Characteristics.Число портов USB Type-A  3.2 Gen 1', 'Characteristics.Число портов USB Type-C', 'Characteristics.Устройства ручного ввода', 'Characteristics.Раскладка клавиатуры', 'Characteristics.Подсветка клавиатуры', 'Characteristics.Цвет клавиатуры', 'Characteristics.Емкость аккумулятора, Втч', 'Characteristics.Тип аккумулятора', 'Characteristics.Гарантийный срок', 'Characteristics.Покрытие экрана', 'Characteristics.Тип видеокарты', 'Characteristics.Бренд графического процессора', 'Characteristics.Тип накопителя', 'Characteristics.Количество SSD', 'Characteristics.Макс. частота обновления, Гц', 'Characteristics.Разрешение Web-камеры', 'Characteristics.Шторка для веб-камеры', 'Characteristics.Встроенные устройства', 'Characteristics.Модуль связи WiFi', 'Characteristics.Особенности устройств ручного ввода', 'Characteristics.Покрытие корпуса', 'Characteristics.Страна-изготовитель', 'Characteristics.Возможность расширения RAM, до', 'Characteristics.Модуль сотовой связи', 'Characteristics.Слоты RAM-памяти', 'Characteristics.Бренд', 'Characteristics.Оптический привод', 'Characteristics.Видеопамять', 'Characteristics.Чипсет', 'Characteristics.Форм-фактор RAM', 'Characteristics.Количество HDD', 'Characteristics.Форм-фактор HDD', 'Characteristics.Конфигурация звука', 'Characteristics.Поддержка VR', 'Characteristics.Кол-во элементов аккумулятора', 'Characteristics.Напряжение адаптера питания', 'Characteristics.Тип подсветки', 'Characteristics.Картридер', 'Characteristics.Конфигурация', 'Characteristics.Сетевая карта', 'Characteristics.Срок службы, лет', 'Characteristics.Версия MacOS', 'Characteristics.Число портов Thunderbolt', 'Characteristics.Число портов USB Type-A 3.2 Gen 2', 'Characteristics.Число портов DisplayPort', 'Characteristics.Общий объем HDD, ГБ', 'Characteristics.Гарантия OZON', 'Characteristics.Тип', 'Characteristics.Вид чехла', 'Characteristics.Материал', 'Characteristics.Застежка', 'Characteristics.Внешние размеры, мм', 'Characteristics.Размеры основного отделения, мм', 'Characteristics.Подходит для устройств', 'Characteristics.Мин. диагональ, дюймы', 'Characteristics.Макс. диагональ экрана, дюймы', 'Characteristics.Вес товара, г', 'Characteristics.Особенности', 'Characteristics.Код ТРУ', 'Characteristics.Сертификат', 'Characteristics.Состав материала', 'Characteristics.Коллекция', 'Characteristics.Стиль', 'Characteristics.Размер на модели', 'Characteristics.Рост модели на фото', 'Characteristics.Параметры модели на фото (ОГ-ОТ-ОБ)', 'Characteristics.Российский размер', 'Characteristics.Размер производителя', 'Characteristics.Пол', 'Characteristics.Материал подкладки', 'Characteristics.Рисунок', 'Characteristics.Модель', 'Characteristics.Особенности модели', 'Characteristics.Тип посадки', 'Characteristics.Тип упаковки одежды', 'Characteristics.Количество в упаковке', 'Characteristics.Уход за вещами', 'Characteristics.Ширина, см', 'Characteristics.Модель ремня', 'Characteristics.Вид пряжки', 'Characteristics.Сезон', 'Characteristics.Покрой', 'Characteristics.Тип рукава', 'Characteristics.Гарантия', 'Characteristics.Сорт цветов', 'Characteristics.Вид выпуска товара', 'Characteristics.Вид мочалки', 'Characteristics.Единиц в одном товаре', 'Characteristics.Упаковка', 'Characteristics.Партномер (артикул производителя)', 'Characteristics.Объем, мл', 'Characteristics.Форма выпуска', 'Characteristics.Основа краски', 'Characteristics.Область применения', 'Characteristics.Степень блеска покрытия', 'Characteristics.Резьба', 'Characteristics.Количество, штук', 'Characteristics.Тип питания', 'Characteristics.Функциональные особенности', 'Characteristics.Конструктивные особенности', 'Characteristics.Режимы работы', 'Characteristics.Максимальная мощность, Вт', 'Characteristics.Тип патрона', 'Characteristics.Крутящий момент, Нм', 'Characteristics.Количество скоростей', 'Characteristics.Макс. обороты на 1ой скорости, об./мин', 'Characteristics.Макс. обороты на 2ой скорости, об./мин', 'Characteristics.Макс. диаметр патрона, мм', 'Characteristics.Напряжение аккумулятора', 'Characteristics.Количество аккумуляторов в комплекте', 'Characteristics.Класс инструмента', 'Characteristics.Партномер', 'Characteristics.Рост', 'Characteristics.Вид застежки', 'Characteristics.Декоративные элементы', 'Characteristics.Размер по вороту', 'Characteristics.Материал стельки', 'Characteristics.Материал подошвы обуви', 'Characteristics.Бренд в одежде и обуви', 'Characteristics.Материал верха', 'Characteristics.Длина стопы, см', 'Characteristics.Вид застёжки', 'Characteristics.Целевая аудитория', 'Characteristics.Количество в упаковке, шт', 'Characteristics.Высота, см', 'Characteristics.Длина, см', 'Characteristics.Праздник', 'Characteristics.Для кого', 'Characteristics.Вид спортивных игр', 'Characteristics.Плотность, г/м2', 'Characteristics.Длина, м', 'Characteristics.Объем, л', 'Characteristics.Способ открытия бака', 'Characteristics.Размещение мусорки', 'Characteristics.Форма мусорного бака', 'Characteristics.Страна бренда', 'Characteristics.Материал подкладки обуви', 'Characteristics.Посадка', 'Characteristics.Тип пронации', 'Characteristics.Спортивное назначение', 'Characteristics.Количество модулей', 'Characteristics.Монтаж', 'Characteristics.Количество рядов', 'Characteristics.Ширина, мм', 'Characteristics.Высота, мм', 'Characteristics.Глубина, мм', 'Characteristics.Тип датчика', 'Characteristics.Вид техники', 'Characteristics.Внутренний материал', 'Characteristics.Полнота', 'Characteristics.Вид рабочей обуви', 'Characteristics.Метод крепления подошвы', 'Characteristics.Длина стельки, см', 'Characteristics.Назначение рабочей обуви', 'Characteristics.Особенности спортивной обуви', 'Characteristics.Глубина, см', 'Characteristics.Ориентация', 'Characteristics.Конструкция стола', 'Characteristics.Макс. нагрузка, кг', 'Characteristics.Материал столешницы', 'Characteristics.Материал фасада', 'Characteristics.Материал подстолья', 'Characteristics.Покрытие', 'Characteristics.Количество ящиков', 'Characteristics.Количество ножек', 'Characteristics.Тип направляющих', 'Characteristics.Толщина столешницы, мм', 'Characteristics.Исполнение', 'Characteristics.Назначение (помещение)', 'Characteristics.Стиль дизайна', 'Characteristics.Форма поставки', 'Characteristics.Особенности конструкции и дизайна', 'Characteristics.Виды парикмахерских ножниц', 'Characteristics.Основной материал', 'Characteristics.Модель ТС', 'Characteristics.Ортопедический', 'Characteristics.Автор на обложке', 'Characteristics.Серия', 'Characteristics.Год выпуска', 'Characteristics.Тип бумаги в книге', 'Characteristics.Тип обложки', 'Characteristics.Тип книги', 'Characteristics.Язык издания', 'Characteristics.Количество страниц', 'Characteristics.Размеры, мм', 'Characteristics.ISBN', 'Characteristics.Сохранность книги', 'Characteristics.Возрастные ограничения', 'Characteristics.Рекомендуемый возраст ребёнка', 'Characteristics.Оригинальное название (для переводных изданий)']

In [120]:
df_laptop = delete_unnecassary_rows_and_columns(df = df_laptop)

In [121]:
laptop_drop_cols = [
    'Characteristics.Обязательные программы предустановлены',
    'Characteristics.Особенности устройств ручного ввода',
    'Characteristics.Конфигурация',
    'Characteristics.Цвет',
    'Characteristics.Цвет клавиатуры',
    'Characteristics.Гарантийный срок',
    'Characteristics.Срок службы, лет',
    'Characteristics.Страна-изготовитель',
    'Characteristics.Напряжение адаптера питания',
    'Characteristics.Тип подсветки',
    'Characteristics.Оптический привод',
    'Characteristics.Поддержка VR',
    'Characteristics.Модуль сотовой связи',
    'Characteristics.Версия Windows',
    'Characteristics.Версия MacOS',
    'Characteristics.Артикул', 'Characteristics.Обязательные программы предустановлены',
    'Characteristics.Конфигурация', 'Characteristics.Встроенные устройства',
    'Characteristics.Особенности устройств ручного ввода',
    'Characteristics.Интерфейсы и разъемы', 'Characteristics.Число портов HDMI', 
    'Characteristics.Число портов USB 2.0', 'Characteristics.Число портов USB Type-A  3.2 Gen 1', 
    'Characteristics.Число портов USB Type-C', 'Characteristics.Число портов Thunderbolt', 
    'Characteristics.Число портов DisplayPort', 'Characteristics.Сетевая карта', 'Characteristics.Картридер',
    'Characteristics.Раскладка клавиатуры', 'Characteristics.Подсветка клавиатуры', 
    'Characteristics.Цвет клавиатуры', 'Characteristics.Покрытие корпуса',
    'Characteristics.Гарантийный срок', 'Characteristics.Гарантия OZON', 
    'Characteristics.Срок службы, лет', 'Characteristics.Страна-изготовитель',
    'Characteristics.Оптический привод', 'Characteristics.Поддержка VR', 
    'Characteristics.Напряжение адаптера питания', 'Characteristics.Шторка для веб-камеры',
    'Characteristics.Интерфейсы и разъемы',
    'Characteristics.Число портов HDMI',
    'Characteristics.Число портов USB 2.0',
    'Characteristics.Число портов USB Type-A  3.2 Gen 1',
    'Characteristics.Число портов USB Type-A 3.2 Gen 2',
    'Characteristics.Число портов USB Type-C',
    'Characteristics.Число портов Thunderbolt',
    'Characteristics.Число портов DisplayPort',
    'Characteristics.Картридер',
    'Characteristics.Сетевая карта',
    'Characteristics.Кол-во элементов аккумулятора',
    'Characteristics.Конфигурация звука',
    'Characteristics.Форм-фактор HDD',
    'Characteristics.Количество HDD',
    'Characteristics.Форм-фактор RAM',
    'Characteristics.Возможность расширения RAM, до',
    'Characteristics.Модуль связи WiFi',
    'Characteristics.Слоты RAM-памяти',
    'Characteristics.Количество SSD',
    'Characteristics.Устройства ручного ввода',
    'Characteristics.Форм-фактор SSD',
    'Characteristics.Форм-фактор ноутбука' ,
    'Characteristics.Модуль связи Bluetooth',
    'Characteristics.Тип аккумулятора'
]


laptop_transformation_dict = {
    'Category': ['category', 'object'],
    'Name': ['name_card', 'object'],
    'Price': ['price', 'int'],
    'Old Price': ['price_old', 'int'],
    'Installment': ['price_installment', 'int'],
    'Rating': ['rating_card', 'float'],
    'Reviews': ['reviews_card', 'int'],
    'Seller': ['name_seller', 'object'],
    'Seller Rating': ['rating_seller', 'float'],
    'Characteristics.Бренд': ['brand', 'object'],
    'Characteristics.Артикул': ['article' , 'int'],
    'Characteristics.Диагональ экрана, дюймы': ['screen_diagonal', 'float'],
    'Characteristics.Разрешение экрана': ['screen_size', 'object'],
    'Characteristics.Технология матрицы': ['matrix', 'object'],
    'Characteristics.Макс. частота обновления, Гц': ['hz_screen', 'int'],
    'Characteristics.Яркость, кд/м2': ['brightness', 'float'],
    'Characteristics.Покрытие экрана': ['screen_coating', 'object'],
    'Characteristics.Сенсорный экран': ['touch_screen', 'object'],
    'Characteristics.Процессор': ['cpu', 'object'],
    'Characteristics.Бренд процессора': ['processor_brand', 'object'],
    'Characteristics.Число ядер процессора': ['processor_cores', 'float'],
    'Characteristics.Модель процессора': ['cpu_model', 'object'],
    'Characteristics.Частота процессора, ГГц': ['ghz_processor', 'float'],
    'Characteristics.Оперативная память': ['ram', 'float'],
    'Characteristics.Тип памяти': ['ram_type', 'object'],
    'Characteristics.Операционная система': ['os', 'object'],
    'Characteristics.Общий объем SSD, ГБ': ['ssd_capacity', 'int'], # Используем internal_storage для совместимости
    'Characteristics.Тип накопителя': ['storage_type', 'object'],
    'Characteristics.Общий объем HDD, ГБ': ['hdd_capacity', 'int'],
    'Characteristics.Видеокарта': ['gpu_full_name', 'object'],
    'Characteristics.Тип видеокарты': ['gpu_type', 'object'],
    'Characteristics.Бренд графического процессора': ['brand_graphic_proccessor', 'object'],
    'Characteristics.Видеопамять': ['video_memory', 'object'],
    'Characteristics.Вес, кг': ['weight_kg', 'float'],
    'Characteristics.Чипсет': ['chipset', 'object'],
    'Characteristics.Время автономной работы, ч': ['auto_time' , 'float'],
    'Characteristics.Материал корпуса': ['case_material', 'object'],
    'Characteristics.Емкость аккумулятора, Втч': ['battery_capacity', 'float'],
    'Characteristics.Разрешение Web-камеры': ['web_camera', 'object'],

}


laptop_repl = ['Characteristics.Оперативная память', 
               'Characteristics.Разрешение Web-камеры' , 
               'Characteristics.Видеопамять' 
               ]

In [122]:
df_laptop[laptop_repl[0]] = convert_to_gb(df_laptop, laptop_repl[0])
df_laptop[laptop_repl[1]] = df_laptop[laptop_repl[1]].str.replace(' Мпикс', '')
df_laptop[laptop_repl[2]] = convert_to_gb(df_laptop, laptop_repl[2])

In [123]:
df_laptop = df_laptop.drop(laptop_drop_cols, axis=1)
df_laptop = transform_dataframe(df_laptop, laptop_transformation_dict)

In [124]:
df_laptop.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5376 entries, 0 to 5410
Data columns (total 39 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   category                  5376 non-null   object
 1   name_card                 4397 non-null   object
 2   price                     2503 non-null   Int64
 3   price_old                 2503 non-null   Int64
 4   price_installment         4378 non-null   Int64
 5   rating_card               2376 non-null   float64
 6   reviews_card              2400 non-null   Int64
 7   name_seller               4397 non-null   object
 8   rating_seller             4195 non-null   float64
 9   URL                       5376 non-null   object
 10  cpu                       4524 non-null   object
 11  ssd_capacity              4752 non-null   Int64
 12  gpu_full_name             4318 non-null   object
 13  os                        4696 non-null   object
 14  screen_diagonal           4789 non-null   float64
 15  ram                       4912 non-null   float64
 16  auto_time                 2515 non-null   float64
 17  weight_kg                 4428 non-null   float64
 18  matrix                    4300 non-null   object
 19  ram_type                  4390 non-null   object
 20  case_material             3784 non-null   object
 21  cpu_model                 4921 non-null   object
 22  processor_brand           4745 non-null   object
 23  ghz_processor             4399 non-null   float64
 24  processor_cores           4600 non-null   float64
 25  screen_size               4688 non-null   object
 26  brightness                1968 non-null   float64
 27  touch_screen              3383 non-null   object
 28  battery_capacity          3311 non-null   float64
 29  screen_coating            4240 non-null   object
 30  gpu_type                  4245 non-null   object
 31  brand_graphic_proccessor  4346 non-null   object
 32  storage_type              4502 non-null   object
 33  hz_screen                 4053 non-null   Int64
 34  web_camera                3421 non-null   object
 35  brand                     2051 non-null   object
 36  video_memory              1278 non-null   object
 37  chipset                   1613 non-null   object
 38  hdd_capacity              233 non-null    Int64
dtypes: Int64(7), float64(10), object(22)
memory usage: 1.7+ MB

In [125]:
for column in df_laptop.columns:
    print(f"Колонка: {column}")
    print(df_laptop[column].unique())
    print("-" * 30)

Колонка: category
['laptop']
------------------------------
Колонка: name_card
['MAIBENBEN Ноутбук 15.6", Intel Core i5-12450H, RAM 8 ГБ 512 ГБ, Intel UHD Graphics, Windows Pro, серый, Русская раскладка'
 'HUAWEI MateBook 14 FLMH-X Ноутбук 14.2", Intel Core Ultra 5 125H, RAM 16 ГБ, SSD 1024 ГБ, Intel Arc Graphics, Без системы, зеленый, Русская раскладка'
 'Apple Ноутбук 11.6", RAM 4 ГБ, SSD 128 ГБ, MacOS, серебристый, Русская раскладка'
 ...
 'Dell Ноутбук 14", Intel Core i7-6600U, RAM 8 ГБ, SSD 256 ГБ, Intel HD Graphics 520, Windows Pro, черный матовый, Английская раскладка'
 'Azerty RB-1452 Ноутбук 14", Intel N95, RAM 16 ГБ, SSD 1024 ГБ, Intel UHD Graphics, Windows Pro, (120-0910), серый, Русская раскладка'
 'MSI Katana 17 B13UCR-1612XRU Ноутбук 17.3", Intel Core i5-13420H, RAM 16 ГБ, SSD 1024 ГБ, NVIDIA GeForce RTX 3050 для ноутбуков (4 Гб), Без системы, (9S7-17L541-1612), черный']
------------------------------
Колонка: price
<IntegerArray>
[   <NA>,  523339,  257297,  227669,  888924,  145303,  966211, 1286411,
  475910, 1345671,
 ...
 1307383,  695587,  231452,  639672,  190102,  638568,  391419,  235618,
  160538,  217809]
Length: 2408, dtype: Int64
------------------------------
Колонка: price_old
<IntegerArray>
[    <NA>,  2251014,   604910,   347918,  1375370,   244674,  1337621,
 11446113,   985528,  2767246,
 ...
  6438649,   854950,   741519,   989621,   344109,  2313783,   475156,
  1928610,   398108,   462624]
Length: 2341, dtype: Int64
------------------------------
Колонка: price_installment
<IntegerArray>
[ 25110,  43612,  27878,  19765,  21442,  35069,  18973,  91859, 137956,
  74077,
 ...
  32619,  78453,  29584,  19635,  90510,  50666,  41074,  13379,  18151,
  54300]
Length: 4115, dtype: Int64
------------------------------
Колонка: rating_card
[5.  nan 4.3 4.5 4.9 4.7 4.8 4.  4.6 3.  4.4 4.1 3.8 1.  4.2 2.7 1.8 2.5
 3.2 3.3 3.4 3.5 3.6 3.7 2.  2.6 2.8 2.9 3.9 2.3 2.2 3.1]
------------------------------
Колонка: reviews_card
<IntegerArray>
[   2,   14, <NA>,    3,   13,   47,   18,  230,   22,  199,
 ...
  105,  194,  152,  453,  287, 4706,  569,  515,   83, 4194]
Length: 258, dtype: Int64
------------------------------
Колонка: name_seller
['Sotomania' 'Фирменный магазин H...' 'Comp+' 'Полюс' 'hassenda' 'Матрица'
 'OLOIU' 'Магазин «Relise»' 'Digital Era' 'Позитроника' None 'SKG'
 'LosTelecom' 'MacTop' 'MetaComp' 'НОУТБУК плюс' 'ООО МВЛ'
 'КомпьютерМаркет' 'F5it' 'Золотая рыбка' 'XCOM-SHOP' 'Связной' 'Mascot'
 'Hongjnhahdjaw' 'М.Видео' 'Plata Tech' 'ElectroShop'
 'Правильные ноутбуки S...' 'Омега' 'SamMarkt' 'RBT' 'Ozon Россия'
 'Комп-Бутик' 'MEGASHOP' 'SuperPrice' 'AV Holding Company ...'
 'Интернет Решения' 'Приоритет' 'Lime Store' 'Инновационная торговл...'
 'sen hong' 'Правильные ноутбуки' 'мини ПК Россия' 'БукКомп'
 'ООО "КОНЦЕРН РАКЕТА"' 'Guangzhou Baiman' 'Механический цехv'
 'Lenozon Computer Fa...' 'CN Бутик-магазин' 'NotebookPro' 'Mирон'
 'ULTRA ZEON' 'RTK' 'Цифровой магаз' 'D-Tora' 'Комп Market' 'ЗС-ноутбук'
 'Echips B2B' 'TsyArs' 'FasTeam' 'Русский магазин эле...' 'БИТКОМ'
 'Ninkear Flagship' 'GR Laptop Studio' 'CARBAYTA Laptop Offic...'
 'WildZone' 'SinoTech' 'Machcreator - фирме...' 'VELTRON' 'S-P.Shop'
 'Магазин 3387051' 'Техносила' 'ThinkPad магазин' 'НОТИК' 'GlobalZon'
 'WeComputer' 'Che' 'Lingyun' 'Магазин 4082075' 'бутик-Neobihier'
 'Thunderobot авторизов...' 'Space Laptops' 'Global Cloud Mercha...'
 'App Store' 'Ninkear-ноутбук' 'ADV-Tech' 'Яндекс Фабрика'
 'Machenike - авториз...' 'NQLiy' 'Текки' '1к' 'Новый Магазин Товар...'
 'XCom' 'PartsOkey MRD' 'Мегаполис' 'ExpertBook' 'Официальный магазин...'
 'МАЙБЕНБЕН' 'Gamma Ray' 'Фирменный магазин э...' 'LSH-lonzuer'
 'ЦифроГрад' 'Айрикс' 'ТехноТрейд' 'IT-shop' 'A-IDA' 'Базар' 'ArtElectro'
 'Настольное решение-...' 'Fix-it' 'ООО "ОТСЕТИ.РУ"' 'E-not ru' 'ITtop'
 'nankeda' 'Компьютерный Цехъ' 'OGW TRADE' 'BELG' 'ЗЕОН' 'Эльдорадо'
 'SmartPC Store Russi...' 'Ozon Казахстан' 'Склад товаров' 'Global Tech'
 'ООО "АРД"' 'RJ-45' 'Guangzhoubaiman' 'ONLY ORIGINAL' 'iGadget-ноутбук'
 'Бук Вам в Дом' 'Ноутбук Предпочитае...' 'XISEZIUO' 'Top\xa0Geek'
 'Креветки' 'ХОБОТ ДОСТАВИТ' 'InSTOCK' 'BestGoods' 'jienfh'
 'ЭкспертТехники' 'ALIKSON' 'Технолайк' 'NRG Mall' 'ЧЕХЛОСЕТЬ РФ'
 'новый продавец комп...' 'Цифровое мышление' 'ROCKETNIKS'
 'Магазин 4311033' 'Overcraft' 'N-Shop' 'Forward Store' 'LEPRO'
 'Волшебный Дом-Ноутбук' 'Linkall' 'ПроНоут и техника' 'Спэйс' 'ARES'
 'LAPTOP KZ' 'Техносэконд' 'Атлас' 'INCEK' 'Techno-torg Laptop'
 'Техника с гарантией' 'Ноутбук Фанатик' 'GURU DEVICE' 'ТехноМаркет'
 '1st Digital' 'ВСЯТЕХНИКА РФ' 'Технологии--Зона для ...' 'K.D.N.'
 'Магазин манго.' 'Цифрозона' 'Fon Line NEW' 'RuVa_Store' 'Docool'
 'Ноутбук Центр' 'ЦИТ' 'LenovoCN' 'ParHome' 'Белый Ветер Цифрово...'
 'ТехноМагазин' 'ЦифраКom' 'компьютерный магази...' 'DepthSeek  Computer'
 'компьютерное короле...' 'LITE-MOBILE' 'ThinkPAD'
 'RZUC цифровая техни...' 'ATAMAI' 'RIKOR' 'Маркетплейс' 'LED TV STORE'
 'Абсолют Трейд' 'САТУРН' 'diMoll' 'PC MOD' 'TEXNIKA_16' 'RS-Eectronics'
 'MICS Distribution' 'Магазин Xiaomi' 'PartsOkey RND' 'Guedun'
 'Ninkear Flagship Mall' 'Рывок вперед' 'Фирменный магазин A...'
 'Компьютерный КОМПлеме...' 'RedComputer' 'CAPPY' 'Магазин Техники'
 'MEIMEI' 'CYBIT' 'Gigabyte Official S...' 'Фирменный магазин T...'
 'ИП Куклин Игорь Валер...' 'Swantech-RU' 'PC World' 'КОМП-АС' 'КРЯ'
 'ydgncd' 'Complink' 'ZT-20CM' 'Viktory Mex' 'бутик-магазин со ск...'
 'Техно_Альянс' 'Электроника-Ninkear' 'Alma' 'Piv Pav Shop'
 'Official laptop store' 'Resy' 'Expert Electronics'
 'Магазин в Средней А...' 'splash' 'Laptop Reseller' 'Comp'
 'SpecialComputers' 'ЭсДжей (SJ)' 'Инклюзивное образован...' 'vhgyeu'
 'SANTIN' 'US Electronics' 'Sunny day' 'Cogis' 'ДиксНоут' 'Fury'
 'TopComputer' 'ООО "МАГ ДЕВАЙС"' 'NewBook' 'Laptop Zona' '1_InnovaShop'
 'Трейд Трекер' 'AliHunt' 'CodeSpark' 'Haier' 'Mijia' 'UniversePC'
 'EVESKY Store' 'Online Центр' 'МВМ' 'Velvet Paradise' 'Bettergoods'
 'Acer - Авторизованн...' 'ТРИКЬЮ (3Q)' 'Кибердисконт 33'
 'MOMEI Техно Лайн' 'Big PineApple' 'MILND GROUP' 'E-BONUS' 'Goolrc'
 'Небесно-голубой Ноутб...' 'IT Club' 'Mars' 'TIMIO GROUP' 'Elgroup'
 'GreenPrice' 'Онуприенко Никита' 'Aurorix' 'Pulser.kz' 'Магазин Mayday'
 'Система' 'ТЕХНИКА % ДАРОМ' 'KVARTON' 'iLord' 'Wazutik' 'ALLTECH'
 'Кремниевый умный ма...' 'Bestsales' 'XFinity Store' 'Ноутленд' 'xurigJI'
 'Tochka store' 'MINIHYPER Official St...' 'Laptop Super Factor...'
 'Магазин электронных...' 'Electro Store' 'dOUyIGS' 'NeoBook'
 'Мир Репитеров' 'ЖЕЛЕЗНЫЙ ДВОРИК' 'XIDIN' 'GadgetVibe'
 'Магазин фабрики тех...' 'MDaai' 'БЭТЕЛЬ' 'OMA official store'
 'Neobihier' 'Мир электроники Маг...' 'Varik' 'laptop' 'DDYSLYJCN Shop'
 'NEOSUN' 'Velinova elcstore' 'Ninkear PC.Russia' 'Chip-Box'
 'Страна игрушек' 'FEDsale' 'Best price' 'ИП Коняшкин' 'Winner Store'
 'Thunderobot фирменн...' 'MAYNICHI' 'Play games on laptop' 'Ноутбукофф'
 'ZHT' 'Серверные Системы' 'ИП Колбешкин' 'Привет технологии'
 'Данис маркет' 'KO&MAR' 'Магазин 4071563' 'HPdiannao'
 'флагманский магазин' 'TopsShops' 'TechnoTOP' 'QEROP' 'Millennium Falcon'
 'ТехноСити' 'Pro Клавиатуры Магази...' 'kdngie' 'Xedon' 'EXPEcomp'
 'Ristoun' 'Зинекс' 'ИП Морозова С.О.' 'Магазин техники' 'Phone-smash'
 'YIMO' 'РазборкаПК' 'Ноут Стар' 'Buyon' 'Евросеть' 'МАКСГАДЖЕТ'
 'ЭЛЕКТРОНИКА' 'ТехникПро' 'Лучшая электроника' 'Бурый Медведь'
 '001 Первый' 'iVika' 'MacStore' 'дисконтный магазин' 'ООО "ТЕХНО-СВЕТ"'
 'Платформа 1' 'sofkom' 'Ninkear ноутбуки' 'ЧОткий' 'WatchMe' 'SULPAK'
 'SituMY' 'MLStore' 'Авелот' 'Avokado' 'PWR computer' 'Магазин 3689280'
 'Lenozon Computer St...' 'магазин аврора' 'ПЛЮС Store' 'iPolly'
 'TECHNOVA' 'Садко Маркет' 'ShadowTech' 'ОЛВИТ' 'Huinamu' 'Интер-М'
 'ТехноЦентр' 'ZharBook' 'Mega Brand' 'KayrosPC' 'Официальный флагман...'
 'ИП Усенко А.В.' 'Laptop Factory' 'VECTOR E' 'VSAP Electronics'
 'Top\xa0Sport' 'PLC-HMI-Lab' 'Blue Sky элeктроник...' 'AFITRON' 'M&K'
 'Folk Laptop' 'Разборка ПК' 'GOLD-PC' 'DogiFlaps' 'LAFADA OFFICE' 'QTECH'
 'GigaMarkt' 'TechPort' 'Минималистский дом' 'SV GoLD StoRe' 'Технологика'
 'Six Shunxing' 'WONTTR 3C' 'ARIANA SHOP' 'XIN Generation магази...'
 'Ninkear Russia' 'BIGDEAL' 'Мирный Атом' 'ХайФренд(Hi.Friend)'
 'Фирменный магазин Hai...' 'Техника' 'DuKon Store' 'Магазин 3762271'
 'Market96' 'uyyuyyh' 'GeekPlace' 'SkyX Retail' 'Inno Tech' 'WENTAI'
 'BotaGo' 'Информ компьютеры' 'palinda' 'OEM' 'Like Electronics'
 'Evolution' '115Shop' 'Абук' 'ПроводОК' 'ТТ OZZ' 'Магазин видеоигр и ...'
 'Chipix-PC' 'CanKu' 'Один нож' 'Good store' 'Musica' 'Котёнок++'
 'OrigProducts' 'WELLSELL' 'ZET-Компьютер' 'TechnoSIB' 'IPC-shopping'
 'Lenozon Russia Stor...' 'MagicBoom' 'Артха' 'МегаФон' 'Уютный дом'
 'Impact' 'Ninkear MiniPc' 'CAN' 'LDMLIKE' 'giper_fm' 'ООО "ИТ Магазин"'
 'Guide' 'Лига Маркет' 'КликМаркет' 'Магазин 4277178' 'КиберСервис'
 'Sundays' 'N&N' 'TechnoHub' 'Lenvoo' 'Topstore' 'ЕЛЕНА электрон' 'REFIT'
 'UltraStore' 'DovbyshPC' 'GSM BUTIK' 'yuzhishangmao' 'Octans' 'HoHolik'
 'Lenozon home' 'ElectroART24' 'BorisovPC' 'ТТ GP'
 'Top Trade Official St...' 'Компас Дисконт' 'HYF990' 'SiLIyun'
 'ARCANE PRODUCT' 'ООО СИТИК' 'Умное превосходство'
 'отборный-Ми-магазин..' 'Levels Plus' 'Rikor Store' 'HuiPu' 'Chuang Bo'
 'Doublekic' 'NovaQ' 'NSPAL' 'Электроник' 'NSGP' 'Second PC'
 'ООО Фирма "РИАН"' 'SHZW' 'Gadget auction' 'Засси loptop' 'SHaoZE'
 'НОУТШОП' 'Магазин-Neobihier' 'NAR-Store' 'NOTIVA' 'ЭЛПО-Сервис'
 'Golden Way' 'Юг Ритейл' 'Холодильник.ру' 'Federal Express'
 'Просто магазин' 'TISHITA' 'R2D2' 'СПИРАЛЬ' 'IT Shop' 'Mac&Phone'
 'F1-KIROV' 'SkyX' 'dONGmiNG' 'YUzIMYgs']
------------------------------
Колонка: rating_seller
[4.8 4.9 4.7 4.6 5.  nan 4.5 4.2 4.4 3.8 1.  4.1 4.3 3.7]
------------------------------
Колонка: URL
['https://www.ozon.kz/product/maibenben-noutbuk-15-6-intel-core-i5-12450h-ram-8-gb-512-gb-intel-uhd-graphics-windows-pro-seryy-3800375233/'
 'https://www.ozon.kz/product/huawei-matebook-14-flmh-x-noutbuk-14-2-intel-core-ultra-5-125h-ram-16-gb-ssd-1024-gb-intel-arc-2401644027/'
 'https://www.ozon.kz/product/apple-noutbuk-11-6-ram-4-gb-ssd-128-gb-macos-serebristyy-russkaya-raskladka-1962208507/'
 ...
 'https://www.ozon.kz/product/dell-noutbuk-14-intel-core-i7-6600u-ram-8-gb-ssd-256-gb-intel-hd-graphics-520-windows-pro-2004565657/'
 'https://www.ozon.kz/product/azerty-rb-1452-noutbuk-14-intel-n95-ram-16-gb-ssd-1024-gb-intel-uhd-graphics-windows-pro-120-3148001514/'
 'https://www.ozon.kz/product/msi-katana-17-b13ucr-1612xru-noutbuk-17-3-intel-core-i5-13420h-ram-16-gb-ssd-1024-gb-nvidia-geforce-3443099695/']
------------------------------
Колонка: cpu
['Intel Core i5-12450H' 'Intel Core Ultra 5 125H' nan
 'Intel Celeron N5095' 'AMD Ryzen 3 4300U' 'AMD Ryzen AI 7 350'
 'AMD Ryzen 5 7520U' 'AMD Ryzen 7 8745HS' 'Intel Pentium N3700'
 'Intel Core Ultra 7 255H' 'Intel Core Ultra 7 255HX'
 'Intel Core i5-8300H' 'Intel Core Ultra 7 155H'
 'Qualcomm Snapdragon X Plus X1P-42-100' 'Intel Core i7-10610U'
 'Intel Core i3-1315U' 'Intel Core i7-7820HQ' 'Intel Core i3-1215U'
 'Apple M5 (10 CPU, 10 GPU)' 'Apple M4 (10C CPU, 10C GPU)'
 'Intel Core L7200' 'Intel Core Ultra 5 225H' 'Intel Core i9-14900HX'
 'AMD Ryzen 7 7730U' 'Intel N150' 'AMD Ryzen 5 7430U'
 'Intel Processor N100' 'Intel Core 5 210H' 'Intel Core i5-1334U'
 'AMD Ryzen 5 240' 'AMD Ryzen 7 8845H' 'AMD Ryzen 7 250'
 'AMD Ryzen 9 8940HX' 'Apple M4' 'Intel Core i5-13420H'
 'AMD Ryzen AI 5 330' 'Intel Core i7-14650HX' 'Intel Core i5-5250U'
 'Intel Core Ultra 9 288V' 'Intel Core Ultra 5 235U' 'Intel Atom N570'
 'Intel Core i7-12700H' 'AMD Ryzen 3 5425U' 'Intel Core i3-1115G4'
 'Intel Core i7-7700HQ' 'Intel Core i5-1240P' 'Intel Core 5 120U'
 'Apple A18 Pro' 'Intel Alder Lake N95' 'Intel Core i3-4010U'
 'AMD Ryzen 5 6600H' 'Intel Core i5-10310U'
 'Apple M5 Pro (15 CPU, 16 GPU)' 'Intel Atom N2800' 'Intel Core i5-11400'
 'AMD Ryzen 3 7320U' 'Intel Core i3-6006U' 'Intel Core Ultra 9 275HX'
 'Intel Core i3-7020U' 'Intel Core i5-8265U' 'Intel Celeron N4500'
 'Intel Core i7-13620H' 'Intel Core i5-6300U' 'AMD Ryzen 5 7535HS'
 'Intel N95' 'Intel Celeron N4020' 'Intel Core i5-1030G4'
 'AMD Ryzen 7 8845HS' 'Intel Core Ultra 5 225' 'Intel Core i5-13500H'
 'Intel Atom N450' 'AMD Ryzen 7 6800H' 'Intel Core i7-6500U'
 'AMD Ryzen 5 150' 'AMD Ryzen 7 7735HS' 'Intel Core Ultra 7 155U'
 'Intel Core Ultra 9 285H' 'Intel Core i7-6600U' 'Intel Core i7-13700HX'
 'Intel Core i5-10210U' 'AMD Ryzen 7 7735U' 'Intel Core i5-1235U'
 'Intel Core i7-8750H' 'Intel Core 7 150U' 'Apple M3 Max (14 CPU, 30 GPU)'
 'AMD Ryzen 5 5500U' 'Intel Core Ultra 5 125U' 'AMD Ryzen 5 1400'
 'Intel Atom N270' 'Intel Core i3-10100Y' 'AMD Ryzen 7 7840HS'
 'Intel Core i5-14450HX' 'Intel Core i5-13450HX' 'Intel Core i5-1335U'
 'Intel Core i5-4210H' 'AMD Ryzen 5 220' 'AMD Ryzen 5 PRO 3500U'
 'AMD A4-9125' 'Apple M3 (8 CPU, 10 GPU)' 'AMD Ryzen 7 260'
 'Intel Core i5-2300' 'Intel Celeron N2830' 'AMD Ryzen 9 8945HX'
 'Intel Core Ultra 9 285HX' 'AMD Ryzen 5 3500U' 'AMD Ryzen 7 5825U'
 'AMD Ryzen 5 7640HS' 'Intel Core i9-13900H' 'Intel Core i7-14700HX'
 'Apple M5 Max' 'AMD Ryzen 7 8840HX' 'AMD Ryzen 7 3700U'
 'Intel Core i9-13900HK' 'Apple M1 Pro (10C CPU, 16C GPU)'
 'AMD Ryzen AI 9 465 ES' 'AMD Ryzen 3 5300U' 'AMD Ryzen AI 5 340'
 'Intel Core 5 225' 'Intel Core i7-1185G7' 'Apple M3 Pro (12 CPU, 18 GPU)'
 'AMD Ryzen 7 PRO 3700U' 'Intel Core Ultra 7 256V' 'Intel Core 3 N355'
 'AMD Ryzen AI 9 HX PRO 370' 'Intel Core i3-2332M'
 'Intel Core Ultra 9 185H' 'Intel Celeron B800' 'Intel Core i5-8259U'
 'AMD Ryzen 3 3200U' 'Intel Core i5-8250U' 'Intel Core i5-1340P'
 'Intel Core i5-7300U' 'Intel Pentium N3710' 'Intel Celeron N5095A'
 'Intel Celeron 5205U' 'AMD Ryzen 7 5800U' 'Apple M5 Pro (18 CPU, 20 GPU)'
 'Intel Core i5-1030NG7' 'Intel Celeron N3350' 'AMD Ryzen 7 5700U'
 'Intel Atom N280' 'Intel Core i3-1220P' 'Intel Core i5-9300H'
 'AMD Ryzen 7 7735H' 'Intel Core 3 100U' 'AMD Ryzen AI 9 HX 370'
 'Intel Core i5-12600H' 'AMD Ryzen 7 8840HS' 'Intel Core 5 220H'
 'Intel Core i7-8550U' 'Intel Pentium Silver N5000' 'Intel Core i3-1125G4'
 'AMD Ryzen AI Max+ 395' 'Apple M4 (10C CPU, 8C GPU)' 'Intel Celeron'
 'AMD Ryzen 7 170' 'Intel Core i5-1155G7' 'AMD Ryzen AI 5 430'
 'Apple M2 (8C CPU, 10C GPU)' 'AMD A4-7210' 'Intel Core i7-5500U'
 'Intel Core i5-1135G7' 'Intel Core i3-N305' 'Intel Core i5-3210M'
 'Intel Core i5-6200U' 'Apple M2' 'Intel Celeron 3855U'
 'Intel Core i5-11400H' 'Intel Core i9-12900HK' 'AMD PRO A10-9700B'
 'Intel Atom N455' 'Intel Core 7 240H' 'AMD Ryzen 5 7235HS'
 'AMD Ryzen 7 7445HS' 'Intel Core i7-1355U' 'AMD Rayzen 7 5825U'
 'Intel Core i5-7300HQ' 'Intel Core i7-9750H' 'AMD Ryzen 3 2200U'
 'Intel Core i3-1005G1' 'Intel Core Ultra 7 258V' 'Intel Pentium J3710'
 'AMD Ryzen 5 5560U' 'AMD Ryzen 5 5600H' 'Intel Core i7-10510U'
 'Intel Pentium Gold 6500Y' 'Intel Core i5-12450HX'
 'Intel Core i7-13650HX' 'AMD Ryzen 5 7535H' 'AMD Ryzen 5 40'
 'Intel Core i7-8565U' 'Intel Core 9 270H' 'Apple M4 MAX'
 'Intel Alder Lake N100' 'AMD Ryzen 5 7530U' 'AMD Ryzen 5 5600U'
 'AMD Ryzen 9 9955HX3D' 'AMD Ryzen 5 5500H' 'Intel Core i7-13700H'
 'Intel Core i5-1250P' 'Intel Core i5-8365U' 'Intel Atom N2600'
 'Intel Core i3-1305U' 'AMD Ryzen AI 9 365' 'Apple M1 (3.2 ГГц)'
 'AMD Ryzen 5 4600H' 'AMD A10-9600P' 'Apple M2 (8C CPU, 8C GPU)'
 'Qualcomm Snapdragon X X1-26-100' 'Intel Celeron N3450'
 'AMD Ryzen 9 9955HX' 'AMD Ryzen 5 4500U' 'AMD Ryzen 5 2500U'
 'AMD Ryzen 9 7945HX' 'Intel Core i5-7200U' 'Intel Core i7-6700HQ'
 'AMD A6-9220' 'Intel Pentium' 'Apple M3 Max (16 CPU, 40 GPU)'
 'AMD Phenom II N870' 'AMD PRO A10-8700B' 'Apple M5 (10 CPU, 8 GPU)'
 'AMD Ryzen 7 7435HS' 'Intel N200' 'Intel Core i5-5200U'
 'AMD Athlon Gold 3150U' 'Intel Core i7-8650U' 'Intel Core i7-10850H'
 'AMD Ryzen 5 8640HS' 'Apple M1 Pro' 'AMD Ryzen 5 7533HS'
 'Intel Core Ultra 5 115U' 'Intel Core Ultra 9 386H'
 'Apple M1 (8C CPU, 7C GPU)' 'Intel Core i3-7100U' 'Intel Celeron J4105'
 'AMD A4-9120' 'AMD Ryzen 5 8540U' 'Intel Core i5-7Y54'
 'AMD Ryzen 7 4800H' 'Intel Core Ultra 7 355' 'Intel Core i5-1145G7'
 'AMD Ryzen AI 7 H 350' 'Intel Core i7-11800H' 'Intel Pentium N4200'
 'Apple M2 Pro (10C CPU, 16С GPU)' 'Intel Celeron N3050' 'AMD A10-7800'
 'Intel Celeron N4020C' 'Intel Alder Lake N150' 'AMD Ryzen 3 PRO 4450U'
 'Intel Core i9-13900HX' 'Intel Core i5-11300H' 'AMD A6-6310'
 'Intel Celeron N5105' 'Intel Core i5-10200H' 'AMD Ryzen 7 H 255'
 'AMD Ryzen AI 7 260' 'AMD Ryzen 9 7845HX' 'Intel Core i7-7920HQ'
 'Intel Celeron 723' 'Intel Core i7-11370H' 'Intel Jasper Lake N100'
 'Intel Core i3-4030U' 'Intel Core i3-6100' 'Intel Core i7-8665U'
 'AMD Ryzen 5 7535U' 'Intel Core i5-8350U' 'Intel Pentium Silver N6000'
 'AMD Ryzen 7 8745HX' 'Intel Pentium 2020M'
 'Apple M4 Pro (14C CPU, 20C GPU)' 'Intel Core i5-5350U'
 'AMD Ryzen 9 6900HX' 'AMD Ryzen AI 7 445' 'Intel Core Ultra 5 226V'
 'Intel Core i5-1035G1' 'Apple A18' 'Intel Core i3-1000NG4'
 'Intel Pentium 6500Y' 'Intel Pentium Gold 6805' 'Intel Pentium N5000'
 'AMD Ryzen 9 270' 'AMD A6-9225' 'Intel Core i3-3210'
 'Intel Celeron N4120' 'AMD Ryzen 7 4800HS' 'AMD Ryzen 5 8645HS'
 'AMD Ryzen 3 7330U' 'Intel Core i5-11320H' 'Intel Core i3-10100'
 'AMD E1-2100' 'AMD Ryzen AI 7 H 445' 'Intel Core i3-10110U'
 'Intel Core P8400' 'Intel Core i3-2370M' 'Intel Core i7-1060NG7'
 'AMD A6-5350M' 'AMD Ryzen 5 5500' 'Intel Celeron N4000'
 'Intel Core Ultra 7 265U' 'AMD Ryzen 7 PRO 5850U' 'AMD Ryzen 7 PRO 4750U'
 'Intel Core i3-3217U' 'AMD Ryzen 5 7540U' 'AMD Ryzen 3 3250U'
 'Intel Core i5-8279U' 'Intel Core i7-9850H' 'Intel Core i3-6100U'
 'Qualcomm Snapdragon X Elite X1E-78-100' 'Intel Celeron N4100'
 'AMD Ryzen AI 9 300' 'Intel Celeron J4125' 'AMD A4-6210'
 'Intel Core 2 Quad Q8200' 'Apple M4 (8C CPU, 8C GPU)'
 'Intel Core i7-10750H' 'Intel Core Ultra 7 268V' 'AMD Ryzen 5 6600HS'
 'Intel Core Ultra 7 255U' 'Intel Core i7-4702MQ' 'Intel Core i7-1255U'
 'Apple M4 Max (16C CPU, 40C GPU)' 'Intel Celeron N3060'
 'Intel Pentium N5030' 'Intel Core i3-5005U' 'AMD Ryzen AI 9 465'
 'Intel Core i5-1038NG7' 'Intel Core i3-4005U' 'Intel Core i5-7360U'
 'Intel Core i7-11850H' 'Intel 80386' 'Intel Celeron 743'
 'Intel Atom x5-Z8300' 'Intel Core i5-6300HQ' 'AMD Ryzen 7 PRO 7840HS'
 'AMD Ryzen 5 PRO 5650U' 'Intel Pentium 4415U' 'Apple M4 Pro'
 'Apple M3 Pro (11 CPU, 14 GPU)' 'AMD Ryzen AI 7 PRO 350'
 'AMD Ryzen 5 3500 Processor' 'Intel Pentium P6300'
 'AMD Ryzen 5 PRO 5675U' 'Intel Core i5-4210U' 'Intel Core i5-4200U'
 'Intel Celeron N3160' 'Intel Core Ultra 7 165U'
 'Qualcomm Snapdragon 8cx Gen3' 'Intel Core i5-4200H'
 'AMD Ryzen AI 9 H 465' 'Apple M3 (8 CPU, 8 GPU)' 'Intel Core i3-1025G1'
 'AMD 3015Ce' 'Intel Core i5-12500H' 'AMD Athlon Gold 7220U'
 'AMD Ryzen 7 7840H' 'Intel Celeron J3355' 'Intel Core i5-4300M'
 'AMD Ryzen AI 9 HX 365' 'AMD A4-5000' 'Intel Core i7-13700'
 'AMD A10-6790B' 'Intel Core i7-1160G7' 'Intel U300'
 'Intel Core Ultra 7 165H' 'Intel Core i5-14500HX' 'AMD Ryzen AI 9 HX 470'
 'Intel Core i3-3110M' 'Apple M4 Max (14C CPU, 32C GPU)'
 'Intel Xeon W-1250P' 'Intel Core i7-12650H' 'AMD Ryzen 9 6980HX'
 'Intel Core i5-3317U' 'AMD Ryzen 7 3750H' 'AMD Athlon Silver 3050U'
 'Apple M1 Pro (8C CPU, 14C GPU)' 'AMD Ryzen 3 5400U'
 'Intel Core i7-7500U' 'Intel Pentium N6000']
------------------------------
Колонка: ssd_capacity
<IntegerArray>
[ 512, 1024,  128, <NA>, 2048,  256, 1000,  320,  120,  248,  275,  500, 2000,
  240,  480,   32, 1020,  250, 4096,   64,  192,  255,   30, 4000,  150,  152,
   51,  523,  125,  215,  508,  257,  200,  528,  522]
Length: 35, dtype: Int64
------------------------------
Колонка: gpu_full_name
['Intel UHD Graphics' 'Intel Arc Graphics' nan 'AMD Radeon'
 'Intel HD Graphics' 'AMD Radeon Graphics' 'AMD Radeon 860M'
 'AMD Radeon 610M' 'AMD Radeon 780M' 'Apple M5'
 'NVIDIA GeForce RTX 5070 Ti для ноутбуков (12 Гб)'
 'NVIDIA GeForce GTX 1050 (4 Гб)' 'Qualcomm Adreno'
 'Intel Iris Xe Graphics' 'AMD Radeon Pro 560 (4 Гб)'
 'Apple M5 GPU (10-core)' 'Apple M4 GPU (10-Core)'
 'NVIDIA GeForce RTX 5070 для ноутбуков (8 Гб)'
 'Intel UHD Graphics Xe 24EUs'
 'NVIDIA GeForce RTX 3050 для ноутбуков (4 Гб)'

In [126]:
df_smartphone.to_csv('../data/processing/not_fully/smartphones.csv', index=False, encoding='utf-8-sig')
df_tablet.to_csv('../data/processing/not_fully/tablets.csv', index=False, encoding='utf-8-sig')
df_laptop.to_csv('../data/processing/not_fully/laptops.csv', index=False, encoding='utf-8-sig')

In [127]:
df_smartphone.to_json('../data/processing/not_fully/smartphones.json', orient='records', force_ascii=False)
df_tablet.to_json('../data/processing/not_fully/tablets.json', orient='records', force_ascii=False)
df_laptop.to_json('../data/processing/not_fully/laptops.json', orient='records', force_ascii=False)